### ISSUE TITLE
Fail to import other plugins with ckeditor-vue comp

### ISSUE THREAD

**Issue by ccksfh** [ckeditor/ckeditor5-vue#10]
If I use ckeditor5-vue as my editor component,when I want to add Other plugins(except for buildIn plugins) like Alignment/Font, it failed

You can see this issue I posted to the repo of ckeditor5-alignment, code is included
[ linked issue](https://github.com/ckeditor/ckeditor5-alignment/issues/30)

Help wanted Please

If this can be solved quickly, I would be soooo appreciate it

**Comment by pomek** [comment]
See https://github.com/ckeditor/ckeditor5-react/issues/21#issuecomment-409347331. In this issue, we resolved the same issue.
