### ISSUE TITLE
No Content & Uncaught CKEditorError: model-nodelist-offset-out-of-bounds

### ISSUE THREAD

**Issue by gmuehl** [ckeditor/ckeditor5-vue#105]
I have a strange Problem with a Custom Build of CKEditor 5. I changed anything in Vue as described here:

https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source

I can serve and Build the App without any Errors or Warnings. The CKeditor shows up and the Toolbar is shown too. I set TEST as Content for the Moment. Though, TEST is not shown in the Content Area:

![image](https://user-images.githubusercontent.com/151238/68758815-cd2feb80-060e-11ea-8793-a10714647245.png)

Now several Things happen:

- TEST is injected via a Variable as V-Model
- TEST is NOT Shown in the Editor
- If i add some new Content, the V-Model gets no Update
- If i add some new Content, i get this Error while typing:

`ckeditorerror.js?ff4e:129 Uncaught CKEditorError: model-nodelist-offset-out-of-bounds: Given offset cannot be found in the node list. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-nodelist-offset-out-of-bounds
`

As i have said, i have no Build-Errors and no Errors in the Console as long as i don't type.

I am not sure if it is a CKEditor-Error or if it is something to do with the Vue-Plugin, i leave this here for the Beginning. What could be Wrong? It must be something with the Custom Build, if i use the CKEditor as compiled Build everything works es expected.

**Comment by Mgsy** [comment]
Hi, did you add Paragraph plugin to your editor?

**Comment by gmuehl** [comment]
Okay, nice hint, anything works as expected with the Paragraph Plugin! Thanks!
