### ISSUE TITLE
Remove formating on pasting from other page

### ISSUE THREAD

**Issue by svkmedia** [ckeditor/ckeditor5-vue#109]
Is it possible to remove formating when pasting data into editor from other website?
I'm using paste from word plugin and it's working like expected. But when I paste any text from other website this text gets html around 

`<span style="color: #000">text</span>`

It's strange because when I check source code of page where I copy text there isn't any HTML. It's just text inside plain <p> tag...

**Comment by FilipTokarski** [comment]
Hi!
Thanks for reporting this issue. I just checked copying&pasting from other websites and it seems to be working fine. Could you please provide some more detailed steps of how to reproduce this behaviour? It would be also helpful to know, what content are you pasting and whether the same happens when you don't use Pase From Office plugin.

**Comment by svkmedia** [comment]
@FilipTokarski I'm not sure if I'm using Paste From Office plugin right way. Anyway this wasn't copied from Office but from website. This is my editor config:

`editorConfig() {
                return {
                    language: this.getLang,
                    heading: {
                        options: [
                            { model: 'paragraph', title: this.trans.get('admin.paragraph'), class: 'ck-heading_paragraph' },
                            { model: 'heading1', view: 'h1', title: this.trans.get('admin.heading') + ' 1', class: 'ck-heading_heading1' },
                            { model: 'heading2', view: 'h2', title: this.trans.get('admin.heading') + ' 2', class: 'ck-heading_heading2' },
                            { model: 'heading3', view: 'h3', title: this.trans.get('admin.heading') + ' 3', class: 'ck-heading_heading2' },
                            { model: 'heading4', view: 'h4', title: this.trans.get('admin.heading') + ' 4', class: 'ck-heading_heading2' },
                            { model: 'heading5', view: 'h5', title: this.trans.get('admin.heading') + ' 5', class: 'ck-heading_heading2' },
                            { model: 'heading6', view: 'h6', title: this.trans.get('admin.heading') + ' 6', class: 'ck-heading_heading2' },
                            { model: 'blockquote', view: 'blockquote', title: this.trans.get('admin.blockquote'), class: 'ck-heading_heading2' }
                        ]
                    },
                    plugins: [
                        EssentialsPlugin,
                        BoldPlugin,
                        ItalicPlugin,
                        LinkPlugin,
                        ParagraphPlugin,
                        Alignment,
                        Heading,
                        Font,
                        FontColor,
                        FontBackgroundColor,
                        ListPlugin,
                        FileRepository,
                        CKFinder,
                        Uploadadapter,
                        Image,
                        ImageCaption,
                        ImageStyle,
                        ImageToolbar,
                        ImageUpload,
                        Table,
                        TableToolbar,
                        MediaEmbed,
                        RemoveFormat,
                        Highlight,
                        PasteFromOffice
                    ],
                    toolbar: {
                        items: [
                            'heading',
                            '|',
                            'bold',
                            'italic',
                            'link',
                            '|',
                            'bulletedList',
                            'numberedList',
                            'insertTable',
                            'alignment',
                            '|',
                            'fontColor',
                            'fontBackgroundColor',
                            '|',
                            'ckfinder',
                            'mediaEmbed',
                            'highlight',
                            'removeFormat',
                            '|',
                            'undo',
                            'redo',
                        ]
                    },
                    ckfinder: {
                        uploadUrl: '/ckfinder/connector?command=QuickUpload&type=Files',
                        options: {
                            pass: 'token',
                            token: this.getToken
                        }
                    },
                    table: {
                        contentToolbar: [ 'tableColumn', 'tableRow', 'mergeTableCells' ]
                    },
                    image: {
                        toolbar: [ 'imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight' ],
                        styles: [
                            // This option is equal to a situation where no style is applied.
                            'full',
                            // This represents an image aligned to the left.
                            'alignLeft',
                            // This represents an image aligned to the right.
                            'alignRight'
                        ]
                    },
                    fontColor: {
                        colors: [
                            {
                                color: 'hsl(0, 0%, 0%)',
                                label: 'Black'
                            },
                            {
                                color: 'hsl(0, 0%, 30%)',
                                label: 'Dim grey'
                            },
                            {
                                color: 'hsl(0, 0%, 60%)',
                                label: 'Grey'
                            },
                            {
                                color: 'hsl(0, 0%, 90%)',
                                label: 'Light grey'
                            },
                            {
                                color: 'hsl(0, 0%, 100%)',
                                label: 'White',
                                hasBorder: true
                            },
                        ]
                    },
                    fontBackgroundColor: {
                        colors: [
                            {
                                color: 'hsl(0, 75%, 60%)',
                                label: 'Red'
                            },
                            {
                                color: 'hsl(30, 75%, 60%)',
                                label: 'Orange'
                            },
                            {
                                color: 'hsl(60, 75%, 60%)',
                                label: 'Yellow'
                            },
                            {
                                color: 'hsl(90, 75%, 60%)',
                                label: 'Light green'
                            },
                            {
                                color: 'hsl(120, 75%, 60%)',
                                label: 'Green'
                            },
                        ]
                    },
                    link: {
                        decorators: {
                            isExternal: {
                                mode: 'manual',
                                label: 'Open in a new tab',
                                attributes: {
                                    target: '_blank'
                                }
                            }
                        }
                    }

                }
            }`

**Comment by FilipTokarski** [comment]
Hi!
Thanks for the code sample. If I understood you correctly, it looks like it's normal behaviour in this case, because you are using FontColor and FontBackgroundColor plugins. So when you're pasting a  text into the editor, FontColor plugin wraps it around a `span` with appropriate font color styling.

You can read more about those plugins and how they work in our docs: https://ckeditor.com/docs/ckeditor5/latest/features/font.html

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
