### ISSUE TITLE
Is it possible to access the CKeditor instance?

### ISSUE THREAD

**Issue by ztickm** [ckeditor/ckeditor5-vue#11]
I might be not understanding a lot of things, but I integrated the component as in the [docs](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html) using ES6 Modules, both globally and locally, on a vue-cli-3 project. 
The editor loads normally, I can interact with the `editorData` attribute, but I seem to be limited to that.
  
I found the following line in a stackoverflow [answer](https://stackoverflow.com/a/15067729/3537581):
```CKEDITOR.instances.yourEditorInstance.editable().getText() ```
 Is it possible, using this component, to access similar functionalities related to the instance? Do I need some sort of plugin?

**Comment by oleq** [comment]
Hi @ztickm!

There's no such thing as a global editor registry in CKEditor 5. Check out our [FAQ entry](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#what-happened-to-the-global-windowckeditor-how-to-list-all-instances-of-the-editor) for more information.

It does not mean there's no way to interact with the editor other than data attributes. [CKEditor 5 has tons of API](https://ckeditor.com/docs/ckeditor5/latest/api/index.html)! In this (Vue.js) case, the easiest way to access the editor instance and its API is by the `@ready` event.

Put the `@ready` listener in the template and create the corresponding method:

```html
<template>
    <div id="app">
        <ckeditor :editor="editor" @ready="onEditorReady"></ckeditor>
    </div>
</template>

<script>
    import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

    export default {
        name: 'app',
        data() {
            return {
                editor: ClassicEditor,
                editorData: '<p>Content of the editor.</p>'
            };
        },
        methods: {
            onEditorReady( editor ) {
                console.log( 'Editor is ready.', { editor } );

                // ... use the API of the "editor" object here.
            }
        }
    }
</script>
```



> I found the following line in a stackoverflow [answer](https://stackoverflow.com/a/15067729/3537581):
> `CKEDITOR.instances.yourEditorInstance.editable().getText() `
> Is it possible, using this component, to access similar functionalities related to the instance? Do I need some sort of plugin?

I hope this [SO answer](https://stackoverflow.com/questions/47552095/ckeditor5-get-plain-text) will help you.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.

**Comment by maitrungduc1410** [comment]
For those who having this problem. You should do like this:
```
<ckeditor @input="onEditorInput" @ready="onEditorReady" .....

// your methods
onEditorInput (value) {
  console.log(viewToPlainText(this.editor.editing.view.document.getRoot()))
},
onEditorReady (editor) {
  this.editor = editor
},
```

**Comment by fede-2110** [comment]
> For those who having this problem. You should do like this:
> 
> ```
> <ckeditor @input="onEditorInput" @ready="onEditorReady" .....
> 
> // your methods
> onEditorInput (value) {
>   console.log(viewToPlainText(this.editor.editing.view.document.getRoot()))
> },
> onEditorReady (editor) {
>   this.editor = editor
> },
> ```

Thanks man!
