### ISSUE TITLE
Duplicate Plugins with Source made Editor!!!

### ISSUE THREAD

**Issue by aSoskuthy** [ckeditor/ckeditor5-vue#110]
Hi all, 

Update: **It looks like I can barely use any other plugins at this point, tried a couple more like HorizontalLine, etc nothing.. I could however add StrikeThrough.... its like random but mostly nothing works when trying to add it.** 

I have spent the last couple of days trying to integrate Ckeditor5 Vue version to our solution. 
We are using the inline editor version 4 currently so I had to upgrade to the **source version of inline editor.**
I have followed the guide and quickly realised the only way to go is to build it from source. This was working fine and I was keep adding plugins without any issues until I reached the Base64UploadAdapter and the SimpleImageUploader plugins. I have already managed to add many plugins such as Mention which took a lot of effort to integrate so I don't want to drop this project.

I'm getting this error after trying to use the Base64UploadAdapter:
ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated.

Here is my component which was all fine until the last plugin
![image](https://user-images.githubusercontent.com/20953139/70153357-b6793380-16a6-11ea-9d11-4f5969867b1e.png)

Here is my current config:
![image](https://user-images.githubusercontent.com/20953139/70153403-cf81e480-16a6-11ea-8861-4ce84a7d5fdd.png)

I would include my vue.config.js but It's pointless I followed the offical tutorial (copy paste) and it was working fine until this point.

**Comment by ma2ciek** [comment]
H @aSoskuthy,

Could you show your `package.json` file and list your CKEditor 5 deps here?

**Comment by ma2ciek** [comment]
There's a chance that you have been installing packages in between of our release, so some packages were installed in the previous versions and some in the later versions.

**Comment by aSoskuthy** [comment]
I just noticed that most of my packages I added yesterday were **v15** but the ones i was adding were all v16 and they dont seem to be packward compatible. I have tried an older version for a package that did not work with v16 and it worked... 
![image](https://user-images.githubusercontent.com/20953139/70157575-b6c8fd00-16ad-11ea-9c64-c7ecb47e75a6.png)

**Comment by ma2ciek** [comment]
With our new [version policy](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/versioning-policy.html#why-not-semantic-versioning) we ship all packages in the same version (like Angular, babel and other libraries). So you should either set all to 15.0.0 or 16.0.0. Otherwise, there will be always a risk that some packages will be bundled twice and will result in the broken editor.

**Comment by aSoskuthy** [comment]
Great thanks so I think It's safe to close this. I will upgrade all to 16 and crack on. 
Thanks for the quick response.
