### ISSUE TITLE
Jest Unit test Failed 

### ISSUE THREAD

**Issue by cg-rbezawada** [ckeditor/ckeditor5-vue#119]
Hi,
my test case getting failed where i use ckeditor. 

version: 
 "@ckeditor/ckeditor5-adapter-ckfinder": "^11.0.2",
    "@ckeditor/ckeditor5-alignment": "^11.1.1",
    "@ckeditor/ckeditor5-autoformat": "^11.0.2",
    "@ckeditor/ckeditor5-basic-styles": "^11.1.1",
    "@ckeditor/ckeditor5-block-quote": "^11.1.0",
    "@ckeditor/ckeditor5-ckfinder": "^11.0.2",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.1",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.1",
    "@ckeditor/ckeditor5-easy-image": "^11.0.2",
    "@ckeditor/ckeditor5-editor-classic": "^12.1.1",
    "@ckeditor/ckeditor5-essentials": "^11.0.2",
    "@ckeditor/ckeditor5-font": "^11.1.1",
    "@ckeditor/ckeditor5-heading": "^11.0.2",
    "@ckeditor/ckeditor5-highlight": "^11.0.2",
    "@ckeditor/ckeditor5-image": "^13.1.0",
    "@ckeditor/ckeditor5-link": "^11.0.2",
    "@ckeditor/ckeditor5-list": "^12.0.2",
    "@ckeditor/ckeditor5-mention": "^11.0.0",
    "@ckeditor/ckeditor5-paragraph": "^11.0.2",
    "@ckeditor/ckeditor5-paste-from-office": "^11.0.2",
    "@ckeditor/ckeditor5-table": "^13.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^14.0.0",
    "@ckeditor/ckeditor5-vue": "^1.0.0-beta.2",
```
Test suite failed to run
    D:\EMT_NEW_18_11_2019\node_modules\@ckeditor\ckeditor5-essentials\src\essentials.js:10
    import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
           ^^^^^^
    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at src/components/programs/CustomMessage.vue:587:94
      at Object.<anonymous> (src/components/programs/CustomMessage.vue:654:3) 
```

Please help me for this issue

**Comment by Mgsy** [comment]
Hi, can you share more details about your issue with code samples and steps to reproduce?
