### ISSUE TITLE
document editor in vue js no toolbar

### ISSUE THREAD

**Issue by shadhin-msa** [ckeditor/ckeditor5-vue#120]
I have used vue components with classic & balloon worked fine. Though none of it solve my needs. I tried to use the document option for the "strikethrough" button + the look. But it doesn't work as expected. editor installed fine but without any toolbar. I find in other javascript examples user need point out the toolbar element. I didn't find any way how to do that when i am using vue. there is no directives or component for that

**Comment by Mgsy** [comment]
Hi, as you noticed, you have to put the toolbar in the container manually. It means that you should create two container elements - for the toolbar and for the editable. Please, see the following code example:
```js
<template>
    <div class="document-editor__toolbar"></div>
    <div class="document-editor__editable-container">
        <ckeditor :editor="editor" :config="editorConfig"  @ready="onReady"></ckeditor>
    </div>
</template>

// ...

methods: {
      onReady(editor) {
          const toolbarContainer = document.querySelector(  '.document-editor__toolbar' );
          toolbarContainer.appendChild( editor.ui.view.toolbar.element );
      }
}
```

**Comment by shadhin-msa** [comment]
Thank you for your reply.
I will try it soon.
Just want to know is it something that I could find from the documentation,
but I didn't.
