### ISSUE TITLE
NUXT.JS Upload Adapter

### ISSUE THREAD

**Issue by liamcharmer** [ckeditor/ckeditor5-vue#122]
Unsure how to get the Upload adapter working for nuxt.js?

**Comment by Mgsy** [comment]
Hi! Nuxt.js doesn't work well with CKEditor 5, so there might be some issues. We have a [feature request ](https://github.com/ckeditor/ckeditor5/issues/6071)for introducing the integration, so if you'd like to see it implemented, please add 👍 to the first post.

**Comment by liamcharmer** [comment]
For anyone that is in need of a wysiwyg urgently refer to 

https://github.com/tui-nuxt/editor#%EF%B8%8Feditor
whilst waiting for the CKEditor nuxt integration
