### ISSUE TITLE
steps for installing ckeditor with mathtype in vuejs

### ISSUE THREAD

**Issue by bhavink21** [ckeditor/ckeditor5-vue#126]
> Hi, I managed to run the CKeditor5 build you provided with no errors and MathType is working fine. So I think there may be some issues with your setup and not with CKEditor.

@FilipTokarski  Could you please send me the steps of installation that you followed?

_Originally posted by @bhavink21 in https://github.com/ckeditor/ckeditor5-react/issues/138#issuecomment-585650199_

**Comment by Mgsy** [comment]
@bhavink21, you should [add MathType plugin to the build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build), then integrate it using our [Vue integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-es6-modules) (use path to your custom build, not the default one).

**Comment by bhavink21** [comment]
@Mgsy @FilipTokarski 
I am getting the following error.

****There was a problem initializing the editor. Cross site scripting is only allowed for HTTP.**
Following is the image of the output i am getting.

![ckeditorImage](https://user-images.githubusercontent.com/59194308/74428162-7d1b2c00-4e7e-11ea-9674-69eaf0a6c536.jpg)

**Comment by bhavink21** [comment]
@Mgsy @FilipTokarski here is the code where i added the mathtype type plugin in the build
`
// The editor creator to use.
import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import UploadAdapter from '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import Link from '@ckeditor/ckeditor5-link/src/link';
import List from '@ckeditor/ckeditor5-list/src/list';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';     // <--- ADDED
import MathType from '@wiris/mathtype-ckeditor5/src/plugin';  // <--- ADDED
export default class ClassicEditor extends ClassicEditorBase {}
// Plugins to include in the build.
ClassicEditor.builtinPlugins = [
   Essentials,
   UploadAdapter,
   Autoformat,
   Bold,
   Italic,
   BlockQuote,
   EasyImage,
   Heading,
   Image,
   ImageCaption,
   ImageStyle,
   ImageToolbar,
   ImageUpload,
   Link,
   List,
   Paragraph,
   Alignment,                                                         // <--- ADDED
  MathType                                                            // <--- ADDED
];
// Editor configuration.
ClassicEditor.defaultConfig = {
   toolbar: {
       items: [
           'heading',
           '|',
           'alignment',                                                 // <--- ADDED
           'bold',
           'italic',
           'link',
           'bulletedList',
           'numberedList',
           'imageUpload',
           'blockQuote',
           'undo',
           'redo',
           'MathType',                                           // <--- ADDED
           'ChemType'                                           // <--- ADDED
       ]
   },
   image: {
       toolbar: [
           'imageStyle:full',
           'imageStyle:side',
           '|',
           'imageTextAlternative'
       ]
   },
   // This value must be kept in sync with the language defined in webpack.config.js.
   language: 'en'
};`
