### ISSUE TITLE
Installing a plugin results in error: "Cannot read property 'getAttribute' of null"

### ISSUE THREAD

**Issue by Livijn** [ckeditor/ckeditor5-vue#13]
I am trying to install a plugin using [this guide](https://ckeditor.com/docs/ckeditor5/latest/features/highlight.html#installation).

This is my error: 

> TypeError: Cannot read property 'getAttribute' of null

I am using it like this:

    <template>
        <ckeditor ref="editor" :editor="editor" :config="editorConfig" v-model="value"></ckeditor>
    </template>

And the script:

    import CKEditor from '@ckeditor/ckeditor5-vue';
    import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
    import Highlight from '@ckeditor/ckeditor5-highlight/src/highlight';

    export default {
        components: {
            Ckeditor: CKEditor,
        },
        props: ['value'],
        data() {
            return {
                editor: ClassicEditor,
                editorConfig: {
                    plugins: [ Highlight ],
                    toolbar: [ 'highlight' ],
                }        
            }
        }
    }

**Comment by Reinmar** [comment]
Unfortunately, you can't add plugins to a build. You can read more about installing plugins in this guide: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html

**Comment by Livijn** [comment]
Sadly, this makes it impossible to use with [Laravel Mix](https://github.com/JeffreyWay/laravel-mix).

**Comment by Reinmar** [comment]
Why would it make it impossible? You can create your own build which would work just like any other editor build. If the quick method explained in the guide I sent you is not enough, there's a link to this: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html

**Comment by Livijn** [comment]
Using that results in 

> Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema. - configuration has an unknown property 'chainWebpack'.`

**Comment by Reinmar** [comment]
That's an odd issue because I've never seen this property so it doesn't come from our documentation. I'm afraid you mixed some webpack configurations from many projects.

**Comment by Livijn** [comment]
[In your docs](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#configuring-vueconfigjs) there is a property called just that:

    chainWebpack: config => {
        // Vue CLI would normally use its own loader to load .svg files. The icons used by
        // CKEditor should be loaded using raw-loader instead.
        config.module
            .rule( 'svg' )
            .test( /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/ )
            .use( 'file-loader' )
            .loader( 'raw-loader' );
    }

**Comment by Reinmar** [comment]
Ouch! My bad. Sorry. We changed that guide recently and I didn't read the new version. 

But this is not supposed to be content of the `webpack.config.js` but `vue.config.js`:

> Edit the `vue.config.js` file and use the following configuration.

**Comment by Livijn** [comment]
Oh, I mis read `vue` for `webpack`. Would you suggest me creating a separate package just for building out the editor, then importing the compiled source it into my original project? Would that work? I am not using *Vue CLI*, but instead *Laravel Mix*.

**Comment by Reinmar** [comment]
> Would you suggest me creating a separate package just for building out the editor, then importing the compiled source it into my original project? Would that work?

Yes. That's the easiest choice. And, AFAIR, may be the only option with Laravel where [integrating the editor from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-2-building-from-source) was not possible.
