### ISSUE TITLE
Resize Image not work

### ISSUE THREAD

**Issue by dinho-afsn** [ckeditor/ckeditor5-vue#130]
Is it working but you have no option to resize the image?
I'm having trouble getting resize to work.

https://imgur.com/a/ddcaPLk
the options appear, but the resize does not

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. If you want  to use `ImageResize`, you need to [import the plugin and add it to your editor configuration](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#installation).

**Comment by dinho-afsn** [comment]
Thanks, I downloaded the source, includes the line

import ImageResize from '@ckeditor/ckeditor5-image/src/imageresize';

DecoupledEditor.builtinPlugins = [
ImageResize,...
]
compiled and now everything works!

Thanks for the quick response!
