### ISSUE TITLE
How to emit a event at upload file?

### ISSUE THREAD

**Issue by elalekey** [ckeditor/ckeditor5-vue#132]
I was checking the editor documentation and I can't find anything about what I need... and basically what I need is that WHEN I attach an image either because I dragged it, pressed CONTROL + V or something... it emits an event to be able to adjust it with another component.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. You can use code like this:
- add `@ready` on the editor component
```js
<ckeditor :editor="editor" v-model="editorData" :config="editorConfig" @ready="onEditorReady"></ckeditor>
```
- in `methods` add:
```js
onEditorReady: function( editor ){

    editor.model.document.on( 'change', () => {
        const changes = editor.model.document.differ.getChanges();

        for ( const change of changes ) {
            if ( change.name == 'image' ) {
                  console.log( 'The image has been inserted.' );

                 // do anything you want here
            }
        }
    } )
}
```
This is a basic implementation, so you can modify it according to your needs. Here is the list of some more [component events](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#component-events) you can use.
Hope that helps!

**Comment by elalekey** [comment]
Solved. Thanks.
