### ISSUE TITLE
CKEditor 5 modules duplicated at Mentions

### ISSUE THREAD

**Issue by elalekey** [ckeditor/ckeditor5-vue#133]
Something like the #121 issue.. i'm trying to add a mentions feature but can't run the project by that problem.

> `/* eslint-disable */
>import CKEditor from '@ckeditor/ckeditor5-vue';
>import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
>
>import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
>import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
>import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
>import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
>import Strikethrough from '@ckeditor/ckeditor5-basic-styles/src/strikethrough';
>import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';
>import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder';
>import List from '@ckeditor/ckeditor5-list/src/list';
>import MediaEmbed from '@ckeditor/ckeditor5-media-embed/src/mediaembed';
>import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
>import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';

>export default {
>  components: {
>    ckeditor: CKEditor.component,
>  },
>  data() {
>    return {
>      editor: ClassicEditor,
>      editorConfig: {
>        plugins: [
>          Essentials,
>          Autoformat,
>          Bold,
>          Italic,
>          Strikethrough,
>          Underline,
>          CKFinder,
>          List,
>          MediaEmbed,
>          Paragraph,
>          PasteFromOffice,
>        ],
>        toolbar: {
>          items: [
>            'bold',
>            'italic',
>            'underline',
>            'strikethrough',
>          ],
>        },
>        placeholder: "Ask a question or post an update...",
>      },
>    };
>  },
>  methods: {
>    onReady(editor) {
>     editor.ui.getEditableElement().parentElement.insertBefore(
>        editor.ui.view.toolbar.element,
>        editor.ui.getEditableElement(),
>      );
>      editor.model.schema.extend( 'paragraph', { isLimit: true } );
>    },
>  },
>};

I have this code but nothing is duplicated..

**Comment by FilipTokarski** [comment]
Hi, did you check in your `package.json` whether all ckeditor plugins have the same version ( the latest is 19.0.0 )?

**Comment by elalekey** [comment]
@FilipTokarski 

![image](https://user-images.githubusercontent.com/41456459/81586927-4d4bc980-9384-11ea-8e10-0ae509dfb062.png)

**Comment by FilipTokarski** [comment]
I see that almost all your packages are version 16 and Mention plugin is 18, which causes the error.  They need to have the same version in order to work properly. You can can upgrade all of the packages to the latest version ( 19 ) using tool like [npm-check-updates](https://www.npmjs.com/package/npm-check-updates).

**Comment by FilipTokarski** [comment]
Closed due to lack of activity.

**Comment by Spoonrad** [comment]
I have a similar issue using React.

```
import React from 'react';
import { CKEditor } from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
// import Mention from '@ckeditor/ckeditor5-mention/src/mention';
```

Uncommenting the last line leads to the error: CKEditorError: ckeditor-duplicated-modules
package.json for CKEditor:
```    "@ckeditor/ckeditor5-react": "^3.0.2",
    "@ckeditor/ckeditor5-build-classic": "^27.1.0",
    "@ckeditor/ckeditor5-mention": "^27.1.0"
```

**Comment by FilipTokarski** [comment]
This happens because you're most probably trying to [add a plugin to the build](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules). If you want to customise your react integration, please see docs on [building from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source).

**Comment by pranayjoshi** [comment]
Cke editor Mention vue implementation?
