### ISSUE TITLE
Unknown custom element: <ckeditor> - did you register the component correctly?

### ISSUE THREAD

**Issue by ajmas** [ckeditor/ckeditor5-vue#135]
I am trying to use the component in a Quasar based project, but I am running into the error:

```
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620 [Vue warn]: Unknown custom element: <ckeditor> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <TextEditor> at src/components/MultiFormatTextEditor.vue
       <QCard>
         <QForm>
           <QPage>
             <PageEditor> at src/pages/PageEditor.vue
               <QPageContainer>
                 <QLayout>
                   <MainLayout> at src/layouts/MainLayout.vue
                     <App> at src/App.vue
                       <Root>
```

My boot item is as follows:

```js
import Vue from 'vue'
import CKEditor from '@ckeditor/ckeditor5-vue'

Vue.use(CKEditor)
```

and the code trying to use it:

```vue
<template>
  <q-card class="c-outlined q-ma-sm" bordered>
    <ckeditor if="format === 'html'" :editor="editorForCK"  v-model="content" />
    <q-input v-else label="Content" type="textarea" outlined class="preformatted" v-model="content" flat/>
  </q-card>
</template>

<script>
import ClassicEditor from '@ckeditor/ckeditor5-build-classic'

export default {
  props: {
    content: String,
    format: {
      type: String,
      default: 'html'
    }
  },
  data () {
    return {
      editorForCK: ClassicEditor,
      markdowEditorOptions: {}
    }
  }
}
</script>
```

My dependencies:

    - "@ckeditor/ckeditor5-build-classic": "^19.0.1",
    - "@ckeditor/ckeditor5-vue": "^1.0.1",

I did also try loading the editor locally, but I get the same issue. Can anyone suggest what the issue might be.

**Comment by ajmas** [comment]
I did try using the 'ckedito4-vue' instead and that worked without challenge:

```
import Vue from 'vue'
import CKEditor from '@ckeditor/ckeditor5-vue'

Vue.use(CKEditor)
```

**Comment by Mgsy** [comment]
Hi, thanks for the report. We already have an open issue for Quasar integration, feel free to join - ckeditor/ckeditor5#6389.

> I did try using the 'ckedito4-vue' instead and that worked without challenge:

Do I understand correctly that using CKEditor 4 vue package fixed your problem with CKEditor 5?

**Comment by ajmas** [comment]
I’ll check the other ticket thanks. 

It wasn’t so much a resolution, since I couldn’t use the latest version, but it did allow me to use CKEditor in some form.
