### ISSUE TITLE
The guide to building CKEditor from source is incorrect

### ISSUE THREAD

**Issue by deploystudios** [ckeditor/ckeditor5-vue#144]
I have gone through the guide to building the editor from source so I could use a plugin, which leads me to my first question... Why do you have to build from source to include a plugin?

_I found out why this was when I was looking into the duplicate modules error. Makes sense about the error but no sense in the fact that it's getting that error from your own guide_

First issue is that during the build I get this at 40%:
`[CKEditorWebpackPlugin] Error: No JS asset has been found during the compilation. You should add translation assets directly to the application from the `translations` directory. If that was intentional use the `buildAllTranslationsToSeparateFiles` option to get rif of the error.
[CKEditorWebpackPlugin] Error: No translation has been found for the en language.`

Second issue is at 92%:
`[CKEditorWebpackPlugin] Error: Too many JS assets has been found during the compilation. You should add translation assets directly to the application from the `translations` directory or use the `addMainLanguageTranslationsToAllAssets` option to add translations for the main language to all assets or use the `buildAllTranslationsToSeparateFiles` if you want to add translation files on your own.`

Third issue is that I get this when I try to use the editor:
`
./node_modules/@ckeditor/ckeditor5-link/theme/linkform.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??ref--6-oneOf-3-2!./node_modules/@ckeditor/ckeditor5-link/theme/linkform.css)
Module not found: Error: Can't resolve './@ckeditor/ckeditor5-ui/theme/mixins/_rwd.css' in '/....../node_modules/@ckeditor/ckeditor5-link/theme'
`

There is no need to attach any files because they're the exact same code that you've listed on this page:
[vue Using CKEditor from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source)

I have zero clues what is going on with the translations but the out of the box implementation shouldn't be doing that.

In terms of the `_rwd.css`, the file is indeed in the location that it says it is not and the import statement in linkform.css points to `@import "@ckeditor/ckeditor5-ui/theme/mixins/_rwd.css";`

**Comment by deploystudios** [comment]
Another error worth mentioning:
Another error that pops up:

`Uncaught CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules`

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I just checked [building editor in Vue from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source) and didn't have any [duplicated modules error](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules) or other problems in running and using the editor ( either dev or production build ).  
As it comes to _JS assets_ errors, we are aware of this and [tracking it here](https://github.com/ckeditor/ckeditor5-vue/issues/134).
I guess there might be something wrong on your side, so maybe you could double check or show your editor component configuration, `vue.config.js` and `package.json`, so we could look into this issue.

**Comment by FilipTokarski** [comment]
Closing due to lack of feedback.

**Comment by soletan** [comment]
Hey, just stumbled over similar issue. In the docs installing theme-lark is given as an example for what I might be interested in installing ("necessary for your integration"), right after setting up vue.config.js. However, theme-lark is used in vue.config.js already and thus should be part of "necessary dependencies" or at least should be separated as an option one might choose from but probably has to pick.
