### ISSUE TITLE
filerepository-no-upload

### ISSUE THREAD

**Issue by crileiton** [ckeditor/ckeditor5-vue#146]
filerepository-no-upload-adapter: Upload adapter is not defined.

**Comment by Mgsy** [comment]
Hi, it seems that your editor doesn't have an upload adapter, so you have to provide one. Please, take a look at our [image upload guide](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/image-upload.html) to learn how to do it.

**Comment by crileiton** [comment]
I am trying to implement SimpleUploadAdapter and I get this error.

CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated

**Comment by Mgsy** [comment]
You probably try to add a plugin directly to the build, which is not allowed. See our [installing plugin guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build) to learn how to do it.

**Comment by crileiton** [comment]
Thank you very much for your help, fix the error

**Comment by Bremmurd** [comment]
filerepository-no-upload-adapter is the error I'm getting
