### ISSUE TITLE
value handler is broken for quick consecutive updates

### ISSUE THREAD

**Issue by Jagholin** [ckeditor/ckeditor5-vue#149]
I have a CMS-like app in which a situation like this happens:

1. User opens a page for editing, CKEditor is opened and some text data is loaded into it. So far so fine.
2. User goes back. Because i use vue router, ckeditor element is 'inactive' but not removed completely.
3. User chooses to open the same page. a) As a precaution(so that the user doesnt see the old content), the editor is cleared with setting its _value_ to some _empty_ string (like '', doesnt matter really). At the same time, a request is sent to the server to fetch a updated version of the page. Because user opened the same page, server responds with the same value as in step 1(this is important). b) If the server responds quickly enough(within 300ms or something), the _value_ handler fails to set the new old text correctly.

because of this line

	if ( newValue !== oldValue && newValue !== this.$_lastEditorData ) {
		this.instance.setData( newValue );
	}

On step 3b, `newValue === this.$_lastEditorData` due to debounce in _change:data_ handler. Furthermore, if we try to wait and set value again, `newValue === oldValue` will be true, making the situation more difficult to recover from.

Not to mention that this also breaks the sync between the state of Vue Element ckeditor and CKEditor's internal state.

**Comment by FilipTokarski** [comment]
cc @oleq can you take a look at this?

**Comment by oleq** [comment]
I confirm the issue. I also found the solution: it is as easy as adding `options.leading=true` to the `debounce()` so it always gets executed immediately and leaves no room for race conditions.

**Comment by oleq** [comment]
@Jagholin Can you confirm #150 will address your issue?

**Comment by Jagholin** [comment]
Hi, i'm currently moving away from ckeditor, so won't be able to verify this directly

But i think there is still a sequence of events, however improbable, that will trigger the bug. But i'm just running this with my brain so the following might well be nonsensical, since i dont have currently the same setup i think it's easier for you to check this

presume that all of this happens in less than INPUT_EVENT_DEBOUNCE_WAIT ms

 - `value` is set to _'content'_, this triggers `change:data` event, its handler executes immediately(leading: true), `$_lastEditorData` is set to  _'content'_.
 - `value` is set to _''_, `this.instance.setData( '' );` is called, this triggers `change:data` event, handler waits for cooldown timer.
 - `value` is set to _'content'_, `newValue !== this.$_lastEditorData` returns `false` and `setData` is not called
 -  `change:data` handler from two steps ago is called, `$_lastEditorData` is set to ''.

I think you want to preserve the ordering of set/get operations. Lodash _debounce_ returns an object with some useful functions, in particular _flush_. I would call it right at the start of the _value_ method, to make sure that `$_lastEditorData` has always correct value. We dont need to $emit anything while doing so, so i would also make _$emit('input',...)_ conditional on whether we are flushing this from value handler or not.
