### ISSUE TITLE
Extra options on images

### ISSUE THREAD

**Issue by SimonJ** [ckeditor/ckeditor5-vue#151]
Hi,

I Am trying to get more options when the user uploads images to the Editor. but I can't seem to get that extra features on (align left, right), etc.

This is what I have done.

1. Created a custom build (https://github.com/SimonJ/ckeditor5-build-classic/blob/master/src/ckeditor.js)
2. Imported these in my packages.json 
```javascript
"@ckeditor/ckeditor5-build-classic": "github:SimonJ/ckeditor5-build-classic#stable",
"@ckeditor/ckeditor5-vue": "^1.0.1",
```

3. Imported ckeditor5-vue in my main app.js file
```javascript
import CKEditor from '@ckeditor/ckeditor5-vue'
Vue.use(CKEditor)
```
4. imported my custom build in my .vue component
```javascript
<ckeditor v-model="textBlock" :editor="editor" :config="editorConfig"></ckeditor>

import ClassicEditor from '@ckeditor/ckeditor5-build-classic'

// With these settings

 data() {
    return {
      editor: ClassicEditor,
      editorConfig: {
        toolbar: ['heading', 'bold', 'italic', 'imageUpload', 'link', 'bulletedList', 'numberedList', 'indent', 'outdent', 'insertTable', 'alignment', 'fontSize', 'fontColor', 'mediaEmbed', 'highlight', 'blockQuote', 'undo', 'redo'],
        image: {
            toolbar: [ 'imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignCenter', 'imageStyle:alignRight', 'imageStyle:side'],
            styles: ['full', 'alignLeft', 'alignCenter', 'alignRight', 'side']
        },
        heading: {
          options: [
            { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
            { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
            { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
            { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
            { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' },
            { model: 'heading5', view: 'h5', title: 'Heading 5', class: 'ck-heading_heading5' },
            { model: 'heading6', view: 'h6', title: 'Heading 6', class: 'ck-heading_heading6' },
          ],
        },
        mediaEmbed: {
          previewsInData: true,
        },
        simpleUpload: {
          uploadUrl: '/shopadmin/files',
          headers: {
            'X-CSRF-TOKEN': window.Laravel.csrfToken,
          },
        },
        link: {
          addTargetToExternalLinks: true,
        },
      },
 }
}
```

But nothing shows up.
![Skærmbillede 2020-08-30 kl  15 43 02](https://user-images.githubusercontent.com/183790/91660687-98c2e880-ead7-11ea-9654-e7295436329d.png)

Can you guys see what I am missing 😅 

And this I what I want to get
![Skærmbillede 2020-08-30 kl  15 44 30](https://user-images.githubusercontent.com/183790/91660744-c4de6980-ead7-11ea-9e96-0604ac1427e6.png)

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Your toolbar looks like a standard toolbar from the Classic build and in your `editorConfig` I see that the order of toolbar items is different. Are you sure you are passing your custom `editorConfig` to the component? Like here:  
`<ckeditor :editor="editor" v-model="editorData" :config="editorConfig"></ckeditor>`  
  
Apart from this, please keep in mind that the repository you forked is archived and it stopped at editor version 19 ( current is 22 ). If you want to use all the new features I recommend sticking to the newest versions.  
  
Some links you might find helpful:
- [quick start guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html)
- [creating custom builds](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html)
- [adding plugins to the build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html)
- [Vue integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#quick-start)
- [custom editor in Vue](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source)
- [Online builder](https://ckeditor.com/ckeditor-5/online-builder/)

**Comment by SimonJ** [comment]
Hi @FilipTokarski 

Thanks for your message.

I'm sure that it's the right config i load 
```javascript
<ckeditor v-model="textBlock" :editor="editor" :config="editorConfig"></ckeditor>
```

The `editorConfig.toolbar` was just to test something, I've removed that again so now i only have this

```javascript
data() {
    return {
      editor: ClassicEditor,
      editorConfig: {
        image: {
            toolbar: [ 'imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignCenter', 'imageStyle:alignRight', 'imageStyle:side'],
            styles: ['full', 'alignLeft', 'alignCenter', 'alignRight', 'side']
        },
        heading: {
          options: [
            { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
            { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
            { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
            { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
            { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' },
            { model: 'heading5', view: 'h5', title: 'Heading 5', class: 'ck-heading_heading5' },
            { model: 'heading6', view: 'h6', title: 'Heading 6', class: 'ck-heading_heading6' },
          ],
        },
        mediaEmbed: {
          previewsInData: true,
        },
        simpleUpload: {
          uploadUrl: '/shopadmin/files',
          headers: {
            'X-CSRF-TOKEN': window.Laravel.csrfToken,
          },
        },
        link: {
          addTargetToExternalLinks: true,
        },
      },
 }
}
```

Still can't see what am doing wrong.
I have added the ImageToolbar and ImageStyle https://github.com/SimonJ/ckeditor5-build-classic/blob/master/src/ckeditor.js#L21

**Comment by FilipTokarski** [comment]
This is strange, I used your code and the result looks fine:  
  
![vue_imgstyles](https://user-images.githubusercontent.com/34380544/91715023-32000680-eb8d-11ea-973e-d35fa945e774.png)

Please double check if everything on your side is ok ( rebuilding the project, browser cache, etc. ).

**Comment by SimonJ** [comment]
@FilipTokarski I took it out of my bootstrap modal and it works 🤯  Are there any known issues when using it in a Bootstrap modal?

**Comment by FilipTokarski** [comment]
Please check the docs on [compatibility with css frameworks](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/css.html), this might be helpful for your use case.

**Comment by SimonJ** [comment]
@FilipTokarski Thanks a lot 🙏  it all works now

**Comment by FilipTokarski** [comment]
Great to hear that 🎉   I'll close this ticket as solved.
