### ISSUE TITLE
How to use watchdog plugin with ckeditor5-vue

### ISSUE THREAD

**Issue by justlester** [ckeditor/ckeditor5-vue#152]
Hi. I wanted to use the watchdog plugin for my ckeditor5 Vue component. 
I was referring to this [documentation](https://ckeditor.com/docs/ckeditor5/latest/features/watchdog.html#editor-watchdog) but there was nothing about how to add it with the Vue component.

A little help would be appreciated. Thanks!

**Comment by FilipTokarski** [comment]
Hi, currently there is no full support for Watchdog in Vue but we have an [open feature request](https://github.com/ckeditor/ckeditor5/issues/4693) for this, so you can track it there. For now, I'll close this ticket as a duplicate.
