### ISSUE TITLE
Disable the In-Line toolbar and editing, render the content

### ISSUE THREAD

**Issue by samiam9297** [ckeditor/ckeditor5-vue#154]
I'm trying to use CKEditor5 Inline on my Vue SPA to accomplish the following:

**Condition 1:**
If a user is logged in and has edit mode enabled CKEditor5 displays the toolbar and enables content editing.

**Condition 2:**
If a user is logged out OR has edit mode disabled, render the HTML.

Here was my attempt:
```
<template>
    <vx-card :title="editorName" v-if="this.$store.state.EditMode">
        <ckeditor :editor="editor" v-model="editorData" :config="editorConfig"></ckeditor>
    </vx-card>
    <vx-card :title="editorName" v-else>
        <div v-html="editorData"></div>
    </vx-card>
</template>
```

The HTML generated by CKEditor5 does not render correctly in a `v-html` tag though, so I think handling CKEditor5 as described below is my best option:

**Condition 2:**
If a user is logged out OR has edit mode disabled, _CKEditor5 hides the toolbar, and disables content editing._

How can I disable the toolbar and disable content editing?

Here is my original question with much more detail:
https://stackoverflow.com/questions/63344958/inline-editor-disable-editor-and-display-html-vue

**Comment by FilipTokarski** [comment]
Hi, did you try [read-only mode](https://ckeditor.com/docs/ckeditor5/latest/features/read-only.html)? Would it be useful for your use case?

**Comment by samiam9297** [comment]
@FilipTokarski Thanks, this combination gave me the functionality I was looking for.

```
<template>
    <vx-card :title="editorName" v-if="loaded">
        <ckeditor :editor="editor" v-model="editorData" :config="editorConfig" :readonly="editorDisabled" :disabled="editorDisabled" ></ckeditor>
    </vx-card>
</template>

//...
        watch:{
            '$store.state.EditMode'(value, oldValue) {
                if(value) {
                    this.editorDisabled = false;
                } else {
                    this.editorDisabled = true;
                }
            },
        },
//...
```
