### ISSUE TITLE
Vue cli3 Using CKEditor from source fail

### ISSUE THREAD

**Issue by wanghuiwen1** [ckeditor/ckeditor5-vue#16]
I follow this document　[https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source](url)

`error  in ./node_modules/@ckeditor/ckeditor5-basic-styles/theme/icons/italic.svg

Module build failed (from ./node_modules/raw-loader/index.js):
ValidationError: Raw Loader Invalid Options

options should NOT have additional properties

    at validateOptions (/home/wanghuiwen/WebstormProjects/zwapp/node_modules/raw-loader/node_modules/schema-utils/src/validateOptions.js:32:11)
    at Object.rawLoader (/home/wanghuiwen/WebstormProjects/zwapp/node_modules/raw-loader/index.js:14:3)

 @ ./node_modules/@ckeditor/ckeditor5-basic-styles/src/italic/italicui.js 15:0-54 44:30-40
 @ ./node_modules/@ckeditor/ckeditor5-basic-styles/src/italic.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Home.vue?vue&type=script&lang=js&
 @ ./src/components/Home.vue?vue&type=script&lang=js&
 @ ./src/components/Home.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.123:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./node_modules/@ckeditor/ckeditor5-undo/theme/icons/undo.svg

Module build failed (from ./node_modules/raw-loader/index.js):
ValidationError: Raw Loader Invalid Options

options should NOT have additional properties

    at validateOptions (/home/wanghuiwen/WebstormProjects/zwapp/node_modules/raw-loader/node_modules/schema-utils/src/validateOptions.js:32:11)
    at Object.rawLoader (/home/wanghuiwen/WebstormProjects/zwapp/node_modules/raw-loader/index.js:14:3)

 @ ./node_modules/@ckeditor/ckeditor5-undo/src/undoui.js 15:0-47 38:61-69
 @ ./node_modules/@ckeditor/ckeditor5-undo/src/undo.js
 @ ./node_modules/@ckeditor/ckeditor5-essentials/src/essentials.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Home.vue?vue&type=script&lang=js&
 @ ./src/components/Home.vue?vue&type=script&lang=js&
 @ ./src/components/Home.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.123:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./node_modules/@ckeditor/ckeditor5-undo/theme/icons/redo.svg

Module build failed (from ./node_modules/raw-loader/index.js):
ValidationError: Raw Loader Invalid Options

options should NOT have additional properties

    at validateOptions (/home/wanghuiwen/WebstormProjects/zwapp/node_modules/raw-loader/node_modules/schema-utils/src/validateOptions.js:32:11)
    at Object.rawLoader (/home/wanghuiwen/WebstormProjects/zwapp/node_modules/raw-loader/index.js:14:3)

 @ ./node_modules/@ckeditor/ckeditor5-undo/src/undoui.js 16:0-47 39:61-69
 @ ./node_modules/@ckeditor/ckeditor5-undo/src/undo.js
 @ ./node_modules/@ckeditor/ckeditor5-essentials/src/essentials.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Home.vue?vue&type=script&lang=js&
 @ ./src/components/Home.vue?vue&type=script&lang=js&
 @ ./src/components/Home.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.123:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.js`

**Comment by oleq** [comment]
@wanghuiwen1 You're right! We didn't notice that the newest version of `raw-loader` cases some issues. Please downgrade to 0.5.1 and everything should be fine:

```
rm -r node_modules/raw-loader/
npm install --save raw-loader@0.5.1
```

BTW: I updated the project documentation so now it includes that important information (will be published ASAP).

**Comment by jodator** [comment]
@wanghuiwen1 Hi. I've reviewed the guide and this is outcome:
