### ISSUE TITLE
Merge code coverage reports from test runs from both Vue versions

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5-vue#162]
This is the follow up of #160.

After splitting up the test into two separate test runs (one for each Vue version), the code coverage reports are also separated and they produce false results. In my opinion we should merge code coverage reports because the component code targets both Vue versions, so in the same way the total checked code coverage should also reflect that fact.

**Comment by mlewand** [comment]
We already use merging code coverage in [our main's repo CI script](continuous-integration-script.js).

You need to [combine `lcov.info` file](https://github.com/ckeditor/ckeditor5/blob/8dbcf217887f5c2c621d03325f9853ccfde4f60d/scripts/continuous-integration-script.js#L151-L163) created for each run (funny part that it just means literally combine files, there's no need for fancy merge). Then you have to [manually upload the combined file to coveralls](https://github.com/ckeditor/ckeditor5/blob/8dbcf217887f5c2c621d03325f9853ccfde4f60d/scripts/continuous-integration-script.js#L96).

**Comment by psmyrek** [comment]
Since we have separate packages for supporting Vue 2.x and Vue 3+, this issue is no longer valid.
