### ISSUE TITLE
CKEditor Instance

### ISSUE THREAD

**Issue by masoudline** [ckeditor/ckeditor5-vue#166]
How can I use CKEditor.instance after run @blur method?
I need access to editor (like @ready function).

**Comment by FilipTokarski** [comment]
Hi, in such case editor instance is passed as the [second argument](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_document-Document.html#event-event:blur), so in the component you should have something like:
```html
<ckeditor :editor="editor" v-model="editorData" :config="editorConfig" @blur="onEditorBlur"></ckeditor>
```
And then you have event as the first argument and editor instance as the second:
```js
methods: {
    onEditorBlur( event, editorInstance ){
        console.log( event );
        console.log( editorInstance );
        // do anything you want with editor instance
    }
}
```
Hope that helps!

**Comment by masoudline** [comment]
Tnx for your favor dude 💯
