### ISSUE TITLE
@vue/cli and Vue.js@3 produces different results that we have in our docs

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-vue#169]
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v3.html

```
Vue.createApp( { /* options */ } ).use( CKEditor ).mount( /* DOM element */ );
```

While Vue 3 uses `createApp()` function:

```js
import { createApp } from 'vue'
import App from './App.vue'

createApp(App).mount('#app')
```

This guide should be reviewed and updated.

**Comment by psmyrek** [comment]
In the Vue 3 guide there are three places, where `Vue.createApp()` is used, but only the last one should be corrected.
The first two occurrences concern direct script include, where the whole Vue module is available globally as `Vue`.

PR is ready: https://github.com/ckeditor/ckeditor5/pull/8498
