### ISSUE TITLE
Very long initialisation time

### ISSUE THREAD

**Issue by 1dnmr** [ckeditor/ckeditor5-vue#17]
Hi,

really long

**Comment by ma2ciek** [comment]
Could you provide some more details?
Do you bundle the code using some minifier?

**Comment by 1dnmr** [comment]
I have 5-10 instances in my application. App starting time is very long 5-8 second. If replace with any other html editor - starting time become as normal.
Yes, I use minified version build with webpack.

**Comment by 1dnmr** [comment]
@ma2ciek 
If I assign new text I also have need 5-8 sec waiting while it's happening to all instances.

**Comment by oleq** [comment]
@1dnmr I'm afraid without a minimal sample (editor instances + **data you load**) we won't be able to help you out.

Anyway, are you sure it's related to our vue component? Have you tried loading the same data into editors created without the component? Is the initialisation also taking so long?

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
