### ISSUE TITLE
How to render html created by ckeditor?

### ISSUE THREAD

**Issue by rosnaib11** [ckeditor/ckeditor5-vue#175]
Is there a way to render what html created by this plugin? like example html that I saved from database I want to display on my page. If I just fetch and display the style is different. Where is the wrapper with the default style?

**Comment by LukaszGudel** [comment]
Hello. Our editor is using classes to style its content. If you want to use generated html on different page then you need to load additional css styles. [Here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html#the-full-list-of-content-styles) you can find full list of styles used by editor. Note that you need to add `ck-content` class to the container of your content to use those styles.

**Comment by rosnaib11** [comment]
Yeah thanks I already made one I forgot to close
