### ISSUE TITLE
Render CKEditor Data in Vue JS

### ISSUE THREAD

**Issue by bhavink21** [ckeditor/ckeditor5-vue#179]
Hey,
I need to render my **CKEditor** Data on my web page but it's not happening as I am using vuejs, which does not refresh the page it just replaces the components.
My **CKEditor** data also contain **MathML** Formulas.
Need to load it dynamically from the rest API.
Example of data that is stored as the output of CKEditor
`<p><math xmlns="http://www.w3.org/1998/Math/MathML"><msup><mrow><mo>(</mo><mi>a</mi><mo>+</mo><mi>b</mi><mo>)</mo></mrow><mn>2</mn></msup><mo>=</mo><msup><mi>a</mi><mrow><mn>2</mn></mrow></msup><mo>+</mo><mn>2</mn><mi>a</mi><mi>b</mi><mo>+</mo><msup><mi>b</mi><mn>2</mn></msup></math></p>`
rendering MathML can be done using the CDN 
[https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML](url)
but this thing works on page refresh and because VueJS is SPA it does not work there.
@Mgsy @FilipTokarski

**Comment by FilipTokarski** [comment]
Hi, not sure if I understood correctly, but after adding [MathType plugin](https://ckeditor.com/docs/ckeditor5/latest/features/math-equations.html#installation) and [updating Vue webpack config](https://github.com/ckeditor/ckeditor5/issues/2048#issuecomment-553922406) I was able to set data and create a mathematical formula, using the content that you provided. If using `MathType` plugin does not help, we'll need more information about your project/use case and exact steps to reproduce this issue.

**Comment by Mgsy** [comment]
Hi @bhavink21! MathType outputs formulas in MathML format, which currently is supported [only in Firefox and Safari](https://caniuse.com/mathml). It means that you'd need some third-party library that will handle the rendering on your page, e.g. [MathJax](https://www.mathjax.org/).
