### ISSUE TITLE
Vue annoying warnings thrown

### ISSUE THREAD

**Issue by nfplee** [ckeditor/ckeditor5-vue#188]
Could you add `emits: ['ready', 'destroy']` as I'm currently getting the following warnings:

> [Vue warn]: Component emitted event "destroy" but it is neither declared in the emits option nor as an "onDestroy" prop.
> [Vue warn]: Component emitted event "ready" but it is neither declared in the emits option nor as an "onReady" prop.

**Comment by psmyrek** [comment]
Hmm, I am not able to reproduce it on my side. Could you give more details on how you use the component?

**Comment by nfplee** [comment]
They seem to be gone since I've upgrade to the latest version.
