### ISSUE TITLE
Tailwind + Ckeditor

### ISSUE THREAD

**Issue by SupportG** [ckeditor/ckeditor5-vue#189]
Hi. I have problems with css styles when using tailwind.

**Comment by FilipTokarski** [comment]
Hi, could you share any details?

**Comment by ThiagoDOM** [comment]
you should use @tailwindcss/typography

Just install:

`npm install -D @tailwindcss/typography`
Extend config:

```
module.exports = {
  theme: {
    // ...
  },
  plugins: [
    require('@tailwindcss/typography'),
    // ...
  ],
}
```
Add prose class wherever you need, and it ignores tailwind css:

```
<article class="prose">
  {{ markdown }}
</article>
```
credits: [Ruslan Korkin](https://stackoverflow.com/users/1894907/ruslan-korkin) [stackoverflow.com...](https://stackoverflow.com/questions/73686839/how-to-render-ckeditor-5-text-as-it-is-with-tailwind-css/74635161)


I still needed to create this css class for the ckeditor width to work properly:
```
.prose {
    width: 100%;
    display: contents;
}
```
