### ISSUE TITLE
the content of the v-model is not processed by ckeditor on ready

### ISSUE THREAD

**Issue by wc-matteo** [ckeditor/ckeditor5-vue#194]
for example if the initial content contains divs and these are not enabled in cke, they disappear only after the first edit. Is this intended? Is there a recommended way to trigger this behavior? (Right now I'm setting the model to an empty string and then re-applying the content on the next tick inside the ready handler)

`@ckeditor/ckeditor5-vue 2.0.1` / `@ckeditor/ckeditor5-editor-classic 28.0.0`

**Comment by psmyrek** [comment]
The editor does not send the `change:data` event when it converts the unsupported elements to paragraphs during the editor initialization. You can try to listen to the `ready` event and then call `editor.getData()` in your app, which will return the current editor data.

Please let us know if this solves your problem.

**Comment by wc-matteo** [comment]
it does! Thanks
