### ISSUE TITLE
How to build CKEditor from source using vue-cli2?

### ISSUE THREAD

**Issue by Warnier-zhang** [ckeditor/ckeditor5-vue#20]

**Comment by oleq** [comment]
Is it different the [instruction we provided for Vue CLI3](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source)?

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
