### ISSUE TITLE
Is there a submit on "enter" key function?

### ISSUE THREAD

**Issue by macknive** [ckeditor/ckeditor5-vue#200]
I was wondering if there's an option to send the text upon pressing enter. The default ckeditor is creating a new line when enter key is pressed. I cannot seem to find on the docs on how to submit on enter https://ckeditor.com/docs/ckeditor5/latest/api/module_enter_enter-Enter.html

**Comment by FilipTokarski** [comment]
Hi, not sure if this will fit your use case, but you could intercept the the enter key press event, prevent the default behaviour and then implement your solution. You could start with code like this:
```js
editor.editing.view.document.on( 'enter', ( evt, data ) => {
	data.preventDefault();
	evt.stop();

	// Do something here
	console.log( 'Enter key stopped.' );
}, { priority: 'high' } );
```
