### ISSUE TITLE
vue (3.2.31 ) this.$_instance is undefined

### ISSUE THREAD

**Issue by lzaifxz** [ckeditor/ckeditor5-vue#202]
vue (3.2.31 ) this.$_instance is undefined

**Comment by hongquan** [comment]
The [reason](https://vuejs.org/api/options-state.html#data) why it is undefined:

> Properties that start with _ or $ will not be proxied on the component instance because they may conflict with Vue's internal properties and API methods. You will have to access them as this.$data._property.

**Comment by psmyrek** [comment]
Duplicate: https://github.com/ckeditor/ckeditor5-vue/issues/203
