### ISSUE TITLE
TypeError: t is undefined - Vue 3.2.31 / ckeditor5-vue 2.0.1

### ISSUE THREAD

**Issue by GinJus** [ckeditor/ckeditor5-vue#207]
Suddenly the last two days I get the next error:

![t-error](https://user-images.githubusercontent.com/4509115/157853078-78b03dfb-325e-4c69-8386-6c1173ec349c.png)

When I run a minimum configuration with only ckeditor5-build-classic and ckeditor5-vue in the dependencies and the basic script in app.js, I still get this messages.

Downgrading Vue didn't help.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. It looks like it's a duplicate of https://github.com/ckeditor/ckeditor5-vue/issues/203. I'll close this ticket for now.
