### ISSUE TITLE
keydown during I can't get the old data that is returning the deleted data

### ISSUE THREAD

**Issue by hurkan-sert** [ckeditor/ckeditor5-vue#21]
this.$refs.editor.instance.editing.view.document.on('keydown', ( event, data ) => {

console.log(data.domEvent.target.textContent) /* deleted data coming */

/* How do I get data before it is deleted*/
})

**Comment by oleq** [comment]
I'm not sure what you want to do? You'd like to know what the selection was before [`DeleteCommand`](https://ckeditor.com/docs/ckeditor5/latest/api/module_typing_deletecommand-DeleteCommand.html#function-execute) was executed? Or want to know what exactly was deleted?

What do you need that for anyway?

**Comment by hurkan-sert** [comment]
I want to get data before it's deleted.

```js
vm.$refs.editor.instance.editing.view.document.on('keydown', ( event, data ) => {
      if(data.domEvent.keyCode=='8' && data.domEvent.keyCode=='46' )
      {
            console.log(vm.$refs.editor.instance.getData())
      }
})
```
But when I press the 'Backspace' key, it gives the data after it is deleted.

**Comment by oleq** [comment]
Use higher priority

```js
vm.$refs.editor.instance.editing.view.document.on('keydown', ( event, data ) => {
    // ...
}, { priority: 'high' } )
```

to attach a listener before the default action is executed.

**Comment by hurkan-sert** [comment]
it's working thanks...
