### ISSUE TITLE
Vue3 + Vite Costum Ckeditor: error Uncaught (in promise) TypeError: this.editor.create is not a function

### ISSUE THREAD

**Issue by lukaszkurowskilbn** [ckeditor/ckeditor5-vue#233]
Hi,

I have no idea how to deal with the ckeditor from my bild anymore,
I added it according to the instructions on the site:
https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/frameworks/vuejs-v2.html#integrating-a-custom-build-from-the-online-builder

But for the last 4 days I have various problems with running this solution:
I am sending for review the part: "package.json" and the component.

package.json:
```
 "dependencies": {
    "@ckeditor/ckeditor5-basic-styles": "^35.2.1",
    "@ckeditor/ckeditor5-build-classic": "^35.2.1",
    "@ckeditor/ckeditor5-editor-balloon": "^35.2.1",
    "@ckeditor/ckeditor5-vue": "^4.0.1",
    "ckeditor5-custom-build": "file:./ckeditor5",
    "lodash": "^4.17.21",
    "material-design-icons": "^3.0.1",
    "materialize-css": "^1.0.0-rc.2",
    "pinyin": "^2.0.21",
    "uuid": "^9.0.0",
    "vue": "^3.2.38",
    "vue-resizable": "^2.1.7",
    "vuedraggable": "^4.1.0"
  },
  "devDependencies": {
    "@rushstack/eslint-patch": "^1.1.4",
    "@types/node": "^16.11.56",
    "@vitejs/plugin-vue": "^3.0.3",
    "@vue/eslint-config-prettier": "^7.0.0",
    "@vue/eslint-config-typescript": "^11.0.0",
    "@vue/tsconfig": "^0.1.3",
    "eslint": "^8.22.0",
    "eslint-plugin-vue": "^9.3.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.7.1",
    "typescript": "~4.7.4",
    "vite": "^3.0.9",
    "vue-tsc": "^0.40.7"
  }

```
component:
```
<template>
  <div>
    <ckeditor :editor="editor" :config="editorConfig" ></ckeditor>
  </div>
</template>
<script lang="ts">
import CKEditor from "@ckeditor/ckeditor5-vue";
import { containersStore } from "@/stores/containers";
// import BalloonBlockEditor from "@ckeditor/ckeditor5-editor-balloon/src/ballooneditor";
import Editor from 'ckeditor5-custom-build/build/ckeditor';
export default {
  components: {
    ckeditor: CKEditor.component,
  },
  data() {
    return {
      containers: containersStore(),
      dragging: true,
      editor: Editor,
      editorData: "<p>Content of the editor.</p>",
      editorConfig: {
        
      },
    };
  },
  props: {
    htmlText: "",
  },
  mounted() {},
  methods: {},
};
</script>

```
Error:
localhost/:1 Uncaught (in promise) TypeError: this.editor.create is not a function
    at Proxy.mounted (ckeditor.js:88:15)
    at runtime-core.esm-bundler.js:2723:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2697:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:341:32)
    at flushJobs (runtime-core.esm-bundler.js:395:9)

**Comment by mabryl** [comment]
Hi @lukaszkurowskilbn,

Thanks for reaching out. I can see that you're using Vite as your build environment and that's something that, until very recently, we didn't support - we used webpack for all our official integrations.

Having said that, as of Decemeber 22nd, we do have an experimental plugin that allows for building CKEditor 5 from source using Vite. You can lear more about it [here](https://github.com/ckeditor/ckeditor5/issues/9807#issuecomment-1363284224).

I'll be closing this issue now and I encourage you to continue discussing the CKE5 + Vite integration in the linked thread.
