### ISSUE TITLE
Automated tests and coverage fails on Windows

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5-vue#241]
On latest `#master` and on Windows, after migrating the package to TypeScript, there is a strange error thrown after running `npm run test` or `npm run coverage`:

```
$ npm run test

> @ckeditor/ckeditor5-vue@4.0.1 test
> node ./scripts/test.js


START:
Webpack bundling...
Error: EINVAL: invalid argument, mkdir 'C:\Users\<username>\AppData\Local\Temp\_karma_webpack_339567\D:\Projekty\ckeditor5-vue\dist'
```

CI works fine.

**Comment by pomek** [comment]
Is it fixed by https://github.com/ckeditor/ckeditor5-vue/commit/8d6d6f1f6c93d482511eea85807132c3750a8116?

**Comment by psmyrek** [comment]
Yes, it works now 🎉
