### ISSUE TITLE
`emitDebouncedInputEvent` causes performance issue with long and complex content

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-vue#246]
It seems that `emitDebouncedInputEvent` might cause performance issues, as it calls `editor.data.get()`. As the initial debouncing time is set to `300ms`, we might observe a significant performance drop while using the editor with long and more complex content.

Potential solution: make the two-way data binding optional

---

I'm attaching the example project with the content containing big paragraphs with text + inline widgets ([placeholders](https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/implementing-an-inline-widget.html#demo)). After running the project and typing in the editor, the freez should be observed.

[vue-performance.zip](https://github.com/ckeditor/ckeditor5-vue/files/11169524/vue-performance.zip)

**Comment by pomek** [comment]
We resolved a similar issue in the Angular integration. [Reference](https://github.com/ckeditor/ckeditor5-angular/commit/594c044fd49d37bd14b7519ae5eac363384fbf40).

**Comment by martnpaneq** [comment]
Here's the PR for updated docs https://github.com/ckeditor/ckeditor5/pull/13894.
