### ISSUE TITLE
Add link popup have wrong position in Modal with fixed mask

### ISSUE THREAD

**Issue by Yunchitz** [ckeditor/ckeditor5-vue#262]
Steps to reproduce:
- Open ckEditor in custom modal window that has mask style:
 position: fixed;
 top: 0;
 left: 0;
 width: 100%;
 height: 100%;
- Observe ck ck-balloon-panel has -99999px top position but has focus and visible if position changed manually 
Used: "@ckeditor/ckeditor5-vue": "5.1.0", Chrome, Vue3 compat build
Thanks in advance!

**Comment by Witoso** [comment]
Please add more information, visual screens, type of the editor you use. It's hard to figure out what the problem is from your description.

Using the editor in modal, [may require some CSS changes](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/css.html#bootstrap-modals).

**Comment by Yunchitz** [comment]
Thanks for response @Witoso  , seams it is only compat build related issue.
Looks like when we click on link button ckeditor creates popup with class ck-balloon-panel_arrowless with (top: -9999) instead class ck-balloon-panel_arrow_nw and it happened only on screen more then 664px.
Seams we can close the issue as far we create workaround and it should be fixed indirectly after remove compat build and switch to vue mode3. Thx a lot!

**Comment by Witoso** [comment]
Ok, thanks!
