### ISSUE TITLE
Table captions is absent

### ISSUE THREAD

**Issue by Yunchitz** [ckeditor/ckeditor5-vue#265]
Hello guys! Wondering that table captions is absent
Use:  @ckeditor/ckeditor5-vue": "^5.1.0"
Custom editor build where I have include table captions
Thx a lot!

**Comment by Witoso** [comment]
Hey, could you share more details or code snippets of the editor creation? It's extremely hard to debug without information 🙏

**Comment by Yunchitz** [comment]
[ckeditor5-40.0.0-ybw5ajr82noa.zip](https://github.com/ckeditor/ckeditor5-vue/files/13380563/ckeditor5-40.0.0-ybw5ajr82noa.zip)
This is editor that I have created with https://ckeditor.com/ckeditor-5/online-builder/ and have added Table caption plugin
May be it is not the problem of vue, can be issue of ckeditor
Thx a lot

**Comment by Witoso** [comment]
You need to configure the table toolbar in the `ckeditor.ts`

```js
        table: {
            contentToolbar: [
                'toggleTableCaption',
                // ...
           
            ]
        }
```
