### ISSUE TITLE
How to set the height of the editor in Vue3? I set CSS, but none of it worked

### ISSUE THREAD

**Issue by xjie0626** [ckeditor/ckeditor5-vue#267]
this is my code ,I set CSS, but none of it worked，How to modify the height of the editor？

```
<template>
  <div>
    <ckeditor v-model="content" :editor="editor" :config="editorConfig"></ckeditor>
  </div>
</template>
<script setup lang="ts">
import { reactive, computed } from "vue"
import ClassicEditor from "@ckeditor/ckeditor5-build-classic"
const props = defineProps({
  ckeditorValue: {
    type: String,
    require: true
  }
})
const emits = defineEmits<{
  "update:ckeditorValue": [value: string]
}>()
const content = computed({
  get() {
    return props.ckeditorValue || ""
  },
  set(value) {
    emits("update:ckeditorValue", value)
  }
})
const editor = ClassicEditor
const editorConfig = reactive({})
</script>
<style scoped>
.custom-ckeditor /deep/ .ck-content {
  resize: 500px;
}
.ck-editor__editable {
  height: 500px;
}
.ck-editor__editable_inline {
  min-height: 500px;
}
.ck-editor__editable_inline:not(.ck-comment__input *) {
  height: 500px;
  overflow-y: auto;
}
</style>
```

thanks

**Comment by filipsobol** [comment]
Hi :wave:,

Removing the `scoped` attribute from the `<style>` tag solves this issue.

Unfortunately, it doesn't seem possible to use scoped styles to style the editor. Scoped styles depend on the `data-v-xxx` attributes added to HTML elements created and controlled by Vue, but the editor's HTML is not created by Vue.

**Comment by xjie0626** [comment]
@filipsobol thank you very much,this issue is solved
I have another question, I have set up some tools in my toolbar
```
Toolbar:{
Items: ["selectAll", "findAndReplace"]
}
```
and set the editor to read-only and hidden the toolbar. How can I call the method "findAndReplace" of this tool，
for example, this function can be called through my custom button

thanks

**Comment by xjie0626** [comment]
@Witoso Yes, it is only allowed for viewing, but I want to achieve keyword search functionality，this plugin "findAndReplace"  is just right
I set read-only through disabled
`<ckeditor v-model="artForm.content" :editor="editor" :disabled="true"></ckeditor>`

thanks

**Comment by filipsobol** [comment]
You can't run this command in read-only mode. What you can do is disable read-only mode, run the command, and then immediately re-enable read-only mode.

```js
editor.enableReadOnlyMode( 'SOME_UNIQUE_KEY' );

// The editor is in read-only mode. Now, if the user decides to replace some text, you can temporarily disable read-only mode like this:

editor.disableReadOnlyMode( 'SOME_UNIQUE_KEY' );
const data = editor.commands.execute('find', 'SEARCH_TERM');
editor.commands.execute('replaceAll', 'REPLACE_TERM', data.results);
editor.enableReadOnlyMode( 'SOME_UNIQUE_KEY' );
```

**Comment by xjie0626** [comment]
@filipsobol Thank you for your reply
I try to write "editor.commands" ,but there was an error reported ---Attribute 'commands' does not exist on type' typeof Editor '
It seems that this cannot be used in Vue，here is a simple example I wrote
```
<template>
  <div>
    <el-card shadow="hover">
      <el-button type="primary" @click="cellClick()">
        <el-icon><Search /></el-icon>
      </el-button>
    </el-card>
    <el-card shadow="hover">
      <ckeditor v-model="content" :editor="editor" :disabled="isReadOnly" :config="config" />
    </el-card>
  </div>
</template>
<script setup lang="ts" name="searchArt">
import { ref } from "vue"
import ClassicEditor from "@ckeditor/ckeditor5-build-classic"
const editor = ClassicEditor
const config = {
  toolbar: false
}
const isReadOnly = ref(true)
const content = ref("1234567890123")
const cellClick = () => {
  isReadOnly.value = false
  editor.commands.execute("find", "12")
}
</script>
```

**Comment by xjie0626** [comment]
Thank you very much. The problem has been resolved 
This needs to be changed
`editor.value.commands.execute("find", "12");`

**Comment by xjie0626** [comment]
Thank you very much. The problem has been resolved 
This needs to be changed
`editor.value.commands.execute("find", "12");`

**Comment by xjie0626** [comment]
The problem has been solved, thank you very much！
