### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by jeffster9** [ckeditor/ckeditor5-vue#27]
While attempting to use from src, I am receiving this message:

./node_modules/@ckeditor/ckeditor5-ui/theme/components/editorui/editorui.css
Module not found: Error: Can't resolve '../../../../../postcss-loader/lib/index.js' in '/home/user/public_html/admin...com/node_modules/@ckeditor/ckeditor5-ui/theme/components/editorui'

However, the path should be ...postcss-loader/src/index.js

Any clue as to why this may be happening?

**Comment by Mgsy** [comment]
Hi, @jeffster9! Did you check our [Vue.js integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html)? Does this issue occur after following steps provided in docs?

Also, it would be great if you could share with us your `package.json` and `vue.config.js` files to give us more details.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
