### ISSUE TITLE
Check if empty?

### ISSUE THREAD

**Issue by Espumisan** [ckeditor/ckeditor5-vue#28]
Hello!

I can't find a way to tell if CKeditor is empty, because if it is empty it is returning `<p>&nbsp;</p>`.

I found a config **ignoreEmptyParagraph** but it is not working

**Comment by Reinmar** [comment]
Hi! This is a DUP of https://github.com/ckeditor/ckeditor5/issues/401.

Good news is that that issue is already fixed and the new release is coming soon (perhaps tomorrow).
