### ISSUE TITLE
Registering a toolbar button with custom plugin

### ISSUE THREAD

**Issue by deepreshion** [ckeditor/ckeditor5-vue#337]
I'm trying to add a custom button, I'm literally adding the [plugin from the documentation](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/plugins/creating-simple-plugin-timestamp.html#registering-a-toolbar-button)
https://codesandbox.io/p/sandbox/hngrmh

```
class Timestamp extends Plugin {
  init() {
    const editor = this.editor

    editor.ui.componentFactory.add( 'timestamp', () => {
      // The button will be an instance of ButtonView.
      const button = new ButtonView()

      button.set( {
        label: 'Timestamp',
        withText: true
      } )

      // Execute a callback function when the button is clicked
      button.on( 'execute', () => {
        const now = new Date()

        // Change the model using the model writer
        editor.model.change( writer => {
          // Insert the text at the user's current position
          editor.model.insertContent( writer.createText( now.toString() ) )
        } )
      } )

      return button
    } )
  }
}
```

and then add it to the config

```
{
  licenseKey: 'GPL',
  toolbar: ['timestamp'],
  plugins: [Timestamp]
}
```

but as a result I just get the error **CKEditorError: ckeditor-duplicated-modules**

package versions
 "@ckeditor/ckeditor5-vue": "^7.3.0",
 "ckeditor5": "^44.1.0",

**Comment by Mati365** [comment]
@deepreshion 

That import seems to be wrong: `import ButtonView from "@ckeditor/ckeditor5-ui/src/button/buttonview";`. This package should be imported directly from `ckeditor5`, as the NPM package has single output file in dist folder.
