### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by ayiexz** [ckeditor/ckeditor5-vue#38]
Hi,
Is there dark mode feature on this ckeditor??

**Comment by Mgsy** [comment]
Hi, there is no official dark theme for CKEditor 5, but you can create it on your own following our [theme customization guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/theme-customization.html).

P.S. this repository is dedicated to issues related to the integration with Vue.js.
