### ISSUE TITLE
TypeError: Cannot convert undefined or null to object 

### ISSUE THREAD

**Issue by CubaJas** [ckeditor/ckeditor5-vue#39]
```
If i set Set the initial data of the editor = null, editor does not load.
My code 
data () {
  return {
    value: null
  }
}
```
<ckeditor v-model="value"
                      :editor="editor.type"
                      @ready="onReadyEditor"
            />

error in 	editor.setData( this.value );
https://github.com/ckeditor/ckeditor5-vue/blob/1dc60f8a887e063ef63e45a0be8105fdfa1b0d13/src/ckeditor.js#L53

For correct working I have to set value like value: '' or with not empty value

**Comment by Mgsy** [comment]
You can't pass `null` to `setData()` method, because it expects the data to be `String`.

**Comment by geri777** [comment]
It's quite common to have null values in data models - to distinguish unset values from empty strings. 
I think the component should accept null values.

**Comment by YuriiZadorozhnyi** [comment]
I have the same issue in my Angular application - ckeditor/ckeditor5-angular

**Comment by tomastan** [comment]
Agree, it's a bit strange.
The component accepts `undefined`, but does not accept `null` values

**Comment by frazzaglia** [comment]
Hi, is there any news or update about setting null value in ngModel? 
Thanks.
