### ISSUE TITLE
Spread information about the integration

### ISSUE THREAD

**Issue by adelura** [ckeditor/ckeditor5-vue#4]
List integration info on:

- [ ] https://github.com/vuejs/awesome-vue#rich-text-editing
- [ ] others?

**Comment by ma2ciek** [comment]
We can add it also on here: https://github.com/JefMari/awesome-wysiwyg.

But that we should do after the official release, not before. This package isn't published to the NPM yet.

**Comment by Reinmar** [comment]
Closing in favor of https://github.com/ckeditor/ckeditor5/issues/1344.
