### ISSUE TITLE
How to get current cursor position

### ISSUE THREAD

**Issue by riddhiparekh** [ckeditor/ckeditor5-vue#40]
I tried getting the cursor position of editor through many different ways but i am not getting a solution.

In my editor object i always get editor.document is undefined.

Also tried 
```
editor.model.change( writer => {
    writer.insertText( 'Plain text', editor.model.document.selection.getFirstPosition() );
} );
```

But even editor.model is undefined.
What i achieved until now is i can get the offset where cursor is but not specific to line number as below.

`editor.source.selection.getLastPosition().offset`
The attached image shows my editor object.
![Screenshot from 2019-03-18 19-04-46](https://user-images.githubusercontent.com/45178176/54533775-f8473a00-49b0-11e9-90a5-b8d55a6f32b0.png)

I am stuck with this issue please let me know what i am doing wrong here.

**Comment by Mgsy** [comment]
Hello, this repository has been created to track issues related to Vue.js integration, not problems with CKEditor 5 itself. Your question should be asked in the [main CKEditor 5 repository](https://github.com/ckeditor/ckeditor5/issues).

However, take a look at our framework [quick start guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html), After following it, you'll be able to get the position via `editor.model.document.selection.getFirstPosition()`.
