### ISSUE TITLE
Toolbar items

### ISSUE THREAD

**Issue by Espumisan** [ckeditor/ckeditor5-vue#41]
Is it really that hard to add all possible toolbar default items inside documentation?

How can I get source and Maximize buttons there?

**Comment by ctwhome** [comment]
I'm also looking on how to add custom buttons, and how to put the toolbar at the bottom, but passing these parameters to the config object doesn't do anything

**Comment by Mgsy** [comment]
Hi @ctwhome!
>how to add custom button

If you'd like to learn how to add custom buttons to the toolbar, take a look at our [Creating a simple plugin guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html) - it covers this subject. 

>how to put the toolbar at the bottom, but passing these parameters to the config object doesn't do anything

CKEditor 5 doesn't have such a configuration option, but you can use the [decoupled editor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/basic-api.html#example-decoupled-editor) and place the toolbar container below the editable.
