### ISSUE TITLE
ES6 import

### ISSUE THREAD

**Issue by kl3sk** [ckeditor/ckeditor5-vue#5]
Hello,

I'am very exited that you provide an official VueJs implementation of CKEditor5 and thank you for this.
But I want to try i and I didn't achieve.

What I've done:

- [x] Clone this repo
- [x] Build
- [x] copy builded files into my app
- [x] Install classic editor in my app
- [ ] import as a VueJs plugin

```VueJs
import * as ClassicEditor from '@ckeditor/ckeditor5-build-classic'
import { CKEditor } from './thirdparty/ckeditor'

Vue.use(CKEditor, {
  editors: {
    classic: ClassicEditor
  }
})
```

It result this error:

```"export 'CKEditor' was not found in './thirdparty/ckeditor'```

May I do something wrong ?

Nota: 
I tried this too
```VueJs
...
import CKEditor from './thirdparty/ckeditor'
...
```

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
@kl3sk I see that the error is in `./thirdparty/ckeditor`. Can you tell us what it looks like? Is the path OK?

Anyway, **once it is released on npm** (soon), the correct way of using the component is (note the absence of curly braces):

```js
import Vue from 'vue';
import CKEditor from '@ckeditor/ckeditor5-vue';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

Vue.use( CKEditor, {
    editors: {
        classic: ClassicEditor
    }
} );
```

So if you used `npm run build` and the component is in `dist/ckeditor.js`, you should use the following code instead

```js
import Vue from 'vue';
import CKEditor from '/path/to/dist/ckeditor.js';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
```

We're going to release the component and extensive documentation soon. Stay tuned!

**Comment by oleq** [comment]
Can you `console.dir( CKEditor )`?

**Comment by kl3sk** [comment]
``undefined``

**Comment by kl3sk** [comment]
If I `export default CKEditor` inside `./thirdparty/ckeditor.js` the editor appears

**Comment by oleq** [comment]
I think this is a webpack/`vue.config.js` issue. I tried what you did and it failed. But when I used the same file as a symlinked packge in `node_modules` via `@ckeditor/ckeditor5-vue`, it worked like a charm. 

What we build as a component is an UMD module and probably vue cli (webpack) treats it differently when it's in `node_modules/@ckeditor/ckeditor5-vue`.

**Comment by kl3sk** [comment]
I don't have any `vue.config.js` file.
Until you release a NPM package (very soon I hope 😄), I'll keep my "hacky" solution.

It is strange that you don't have the same result.

Just to be clear:
- Clone the depot in a separate folder
- Build it
- Copy de build files in the "main" app

You probably right with the `node_modules/@ckeditor` behavior.

**Comment by oleq** [comment]
> It is strange that you don't have the same result.

I had the same result :( And I'm pretty sure this is something about the way Vue CLI builds the code. It works when in `node_modules/*` but fails for local imports.

**Comment by kl3sk** [comment]
Ok sorry I misunderstood you meanings.

So, I suppose this will work when an NPM package will be released.
Any date ?

**Comment by oleq** [comment]
Good news @kl3sk, we've just [released](https://www.npmjs.com/package/@ckeditor/ckeditor5-vue) the component!

**Comment by kl3sk** [comment]
Yes great new, I'll try it now :D

**Comment by kl3sk** [comment]
NPM package release
