### ISSUE TITLE
how to add plugins of ckeditor in nuxt with ssr

### ISSUE THREAD

**Issue by imsidz** [ckeditor/ckeditor5-vue#54]
i am trying to add Alignment plugins of ckeditor 5 in my nuxt app which is universal (SSR)

i tried like this in plugins

```
import Vue from 'vue'
import ClassicEditor from '@ckeditor/ckeditor5-build-classic'
import VueCkeditor from 'vue-ckeditor5'

// import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment'; <-- not working


const options = {

    editors: {
        classic: ClassicEditor,

    },
    name: 'ckeditor'
}

Vue.use(VueCkeditor.plugin, options);
```

i also tried direct import to page like this

`import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';`

getting error

> Unexpected identifier

Normal editorConfig is working fine

```
editorConfig: {

      image: {

        toolbar: ['imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight'],

                styles: [

                'full',


               'alignLeft',


               'alignRight'
           ]
         },
         alignment: {
           options: [ 'left', 'right' ]
         },
         toolbar: {
           items: [
            'heading',
            'bold',
            'italic',
            'link',
            'bulletedList',
            'numberedList',
            'blockQuote',
            'insertTable',
            'imageUpload',
            'mediaEmbed',
            'alignment'
          ]
       }
    },
```

**Comment by Mgsy** [comment]
Hello, you have to prepare a custom build with alignment plugin. Please, take a look at our [installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html).

**Comment by imsidz** [comment]
i didn't try custom build i am using normal vue ckeditor

**Comment by Mgsy** [comment]
>i didn't try custom build i am using normal vue ckeditor

I understand, but at first, you have to create a custom build with alignment plugin enabled, then import it to your Vue application.

**Comment by imsidz** [comment]
@Mgsy it means i can use external plugins only in custom build ckeditor
