### ISSUE TITLE
Can't add plugins

### ISSUE THREAD

**Issue by AliN11** [ckeditor/ckeditor5-vue#56]
I am trying to add `CKFinder` plugin to the CKEditor. Here is my code:

This is single component file contents, `PageComponent.vue` :
```html
<template>
    <ckeditor :editor="editor" v-model="editorData" :config="editorConfig"></ckeditor>
</template>
```

```javascript

import CKEditor from '@ckeditor/ckeditor5-vue';
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder';


export default {
    components: {
        ckeditor: CKEditor.component
    },
    data() {
        return {
            editor: ClassicEditor,
            editorData: '<p>Content of the editor.</p>',
            plugins: [CKFinder],
            toolbar: ['ckfinder'],
            editorConfig: {
                // The configuration of the editor.
            }
        }
    }
}
```

The problem is that there is nothing on the page. It's like it is hidden. I also have no errors in the console. 

It works and shows the editor if I replace `@ckeditor/ckeditor5-editor-classic/src/classiceditor` with `@ckeditor/ckeditor5-build-classic`, but as you may guess, I get `ckeditor-duplicated-modules` error.

**Comment by Mgsy** [comment]
Hello, you should build the editor from the source. Did you follow [our guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source)?

**Comment by AliN11** [comment]
@Mgsy Thanks for this fast response. I took a look at that. But I didn't know how to include `vue.config.js` file to the app.

**Comment by AliN11** [comment]
Hi. I tried to go with that guide by which rose multiple errors. After doing `npm run dev`, the first error was:
```
ERROR in ./node_modules/@ckeditor/ckeditor5-link/theme/linkform.css (./node_modules/css-loader??ref--7-1!./node_modules/postcss-loader/src??ref--7-2!./node_modules/@ckeditor/ckeditor5-link/theme/linkform.css)
Module not found: Error: Can't resolve './@ckeditor/ckeditor5-theme-lark/theme/mixins/_rwd.css' in 'E:\xampp\htdocs\xampp\external\the-project\node_modules\@ckeditor\ckeditor5-link\theme'
```

Despite I'm sure that the `_rwd.css` file exists, I removed this line:
`@import "@ckeditor/ckeditor5-theme-lark/theme/mixins/_rwd.css"` from `linkform.css` and `linkform.css`

After that, compilation completed successfully. But there was another error. I the browser console I got ` TypeError: "svg is null"`?

Any help? Thanks in advance.

**Comment by Mgsy** [comment]
Can you share your editor configuration code and `vue.config.js` file?

**Comment by AliN11** [comment]
@Mgsy Problem solved. I'm using CKEditor inside a Laravel app. So I had to change the configuration based on [this issue](https://github.com/ckeditor/ckeditor5-vue/issues/23#issuecomment-455756667). It would be good if it mentioned somewhere.

BTW Thanks a lot for your help and attentions.

**Comment by Mgsy** [comment]
I'm glad that you managed to solve your problem. 

About CKFinder - I can't reproduce your issue, after adding CKFinder to the editor (also in Vue integration), the icon is enabled. Did you see our [CKFinder integration guide](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/ckfinder.html)?

**Comment by AliN11** [comment]
@Mgsy I don't know why this is disabled. I'll check your guide and inform you here. Thanks.

**Comment by AliN11** [comment]
Although I followed your guide, that problem (disabled ckfinder icon) existed for `image` plugin too and unfortunately I had to switch to another text editor.
Thanks.

**Comment by Mgsy** [comment]
@AliN11, I'm sorry to hear that you struggled with this problem. However, can I ask you to create a new ticket and describe the exact steps needed to reproduce the issue? It will be very helpful for us, so we'll be able to investigate it and fix the bug (if needed).

**Comment by MarioMunnoz** [comment]
First library that you have to build plugins and stuff from source by yourself.. what a shi... library. Quite difficult to implement..

**Comment by Jeff-Tian** [comment]
> Hi. I tried to go with that guide by which rose multiple errors. After doing `npm run dev`, the first error was:
> 
> ```
> ERROR in ./node_modules/@ckeditor/ckeditor5-link/theme/linkform.css (./node_modules/css-loader??ref--7-1!./node_modules/postcss-loader/src??ref--7-2!./node_modules/@ckeditor/ckeditor5-link/theme/linkform.css)
> Module not found: Error: Can't resolve './@ckeditor/ckeditor5-theme-lark/theme/mixins/_rwd.css' in 'E:\xampp\htdocs\xampp\external\the-project\node_modules\@ckeditor\ckeditor5-link\theme'
> ```
> 
> Despite I'm sure that the `_rwd.css` file exists, I removed this line:
> `@import "@ckeditor/ckeditor5-theme-lark/theme/mixins/_rwd.css"` from `linkform.css` and `linkform.css`
> 
> After that, compilation completed successfully. But there was another error. In the browser console I get ` TypeError: "svg is null"`.
> 
> Any help? Thanks in advance.

I met the exact same issue, can you share how did you fix it?

**Comment by Jeff-Tian** [comment]
OK, fixed by 

```typescript
  chainWebpack(config, { webpack }) {
    config.module
      .rule('ckeditor5css')
      .test(/ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css/)
      .oneOf('normal')
      .use('style-loader')
      .loader('style-loader')
      .end()
      .end()
      .oneOf('postcss')
      .before('normal')
      .use('postcss-loader')
      .loader('postcss-loader')
      .options(
        styles.getPostCssConfig({
          themeImporter: {
            themePath: require.resolve('@ckeditor/ckeditor5-theme-lark'),
          },
          minify: true,
        }),
      );
  }
```
