### ISSUE TITLE
Simple custom plugin causes issues with Link and Table.

### ISSUE THREAD

**Issue by mxmkhv** [ckeditor/ckeditor5-vue#57]
I implement the CKEditor5 from source in my Vue app. I use the **ckeditor5-editor-classic** (following [this guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source)) and want to add a custom button.

I followed this [guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html) and created a simple plugin to console.log on a click of the button. That works just fine.

**The problem:** The moment include my custom plugin, the Link and Table plugins start misbehaving that seems like a css positioning issue (renders the link field on the bottom of the page).

My component looks like this:

```
<template>
    <div>
        <ckeditor
                v-model="body"
                :editor="editor"
                :config="editorConfig">
        </ckeditor>
    </div>
</template>

<script>
    import CKEditor from '@ckeditor/ckeditor5-vue';
    import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
    import EssentialsPlugin from '@ckeditor/ckeditor5-essentials/src/essentials';
    import BoldPlugin from '@ckeditor/ckeditor5-basic-styles/src/bold';
    import LinkPlugin from '@ckeditor/ckeditor5-link/src/link';
    import MyCustomPlugin from '@/components/common/MyCustomPlugin';

    export default {
        components: {
            ckeditor: CKEditor.component,
        },
        data: function() {
            return {
                editor: ClassicEditor,
                editorConfig: {
                    plugins: [
                        EssentialsPlugin,
                        BoldPlugin,
                        LinkPlugin,
                    ],
                    extraPlugins: [MyCustomPlugin,],
                    toolbar: {
                        items: [
                            'bold',
                            'link',
                            'myCustomPlugin'
                        ]
                    }
                },

            };
        },
    };
</script>
```

My vue.config.js file follows the guide. My custom plugin looks like this:

```
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import imageIcon from '@ckeditor/ckeditor5-core/theme/icons/image.svg';
import ButtonView from '@ckeditor/ckeditor5-ui/src/button/buttonview';

class MyCustomPlugin extends Plugin {
    init() {
        const editor = this.editor;

        editor.ui.componentFactory.add( 'myCustomPlugin', locale => {
            const view = new ButtonView( locale );

            view.set( {
                label: 'Insert image',
                icon: imageIcon,
                tooltip: true
            } );

            view.on( 'execute', () => {
                console.log('dispatch some event');
            } );

            return view;
        } );
    }
}

export default MyCustomPlugin;
```

I have the following dependencies:

   ```
 "@ckeditor/ckeditor5-basic-styles": "^11.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.1",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.1",
    "@ckeditor/ckeditor5-editor-classic": "^12.0.0",
    "@ckeditor/ckeditor5-essentials": "^11.0.0",
    "@ckeditor/ckeditor5-font": "^10.0.4",
    "@ckeditor/ckeditor5-highlight": "^11.0.0",
    "@ckeditor/ckeditor5-link": "^11.0.0",
    "@ckeditor/ckeditor5-paragraph": "^11.0.0",
    "@ckeditor/ckeditor5-vue": "^1.0.0-beta.1",
```

The only indication I have is when ButtonView is not included, the Link seems to work properly.

Otherwise no error messages. I haven't included the **ckeditor5-build-classic** anywhere else in the app.

I have spent some few days on this issue and have tried everything the web has to offer, but cannot seem to find a way forward. Any help would be appreciated!

**Comment by Mgsy** [comment]
Hi, I've checked your plugin and it works totally fine. I see that your dependencies are outdated, so updating them should solve your issue. You can use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates).

**Comment by mxmkhv** [comment]
That solved it! 

I have previously tried updating all dependencies, but back then I was including both the **ckeditor5-build-classic** and the **ckeditor5-editor-classic**. 

Thanks a lot for the help and quick response! :)

**Comment by caiokawasaki** [comment]
@Mgsy inside the plugin, how to emit a vue event in this code part: ?

```
view.on( 'execute', () => {
               Vue.$emit('custom-event')
                console.log('dispatch some event');
            } );
```
