### ISSUE TITLE
Custom build breaks ~@ alias

### ISSUE THREAD

**Issue by agronick** [ckeditor/ckeditor5-vue#59]
I've been stuck on this for a few days. Hoping someone could shed some light on it. I'm trying to do the custom build.

When I add this block to my Vue.config.js all my aliases in my sass files that map ~@ to src/ break.
```
  css: {
    loaderOptions: {
      // Various modules in the CKEditor source code import .css files.
      // These files must be transpiled using PostCSS in order to load properly.
      postcss: styles.getPostCssConfig({
        themeImporter: {
          themePath: require.resolve('@ckeditor/ckeditor5-theme-lark'),
        },
        minify: true,
      }),
    },
  },
```

Here is the error message:
```
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find '~@/assets/slim_table.css'
```

I've tried setting
```
  configureWebpack: {
    resolve: {
      alias: {
        '~': path.resolve(__dirname, 'src/'),
        '~@': path.resolve(__dirname, 'src/'),
      },
    },
  },
```
And
```
  chainWebpack: config => {
    config.resolve.alias
      .set('@', path.resolve(__dirname, 'src/'))
      .set('~@', path.resolve(__dirname, 'src/'));
}
```

And it still doesn't work. Any idea why that is? 

Thank you and thanks for the awesome editor.

**Comment by Mgsy** [comment]
@ma2ciek, can you look at this one?

**Comment by ma2ciek** [comment]
Hi @agronick.

I don't understand actually what you want to achieve. You talk about SCSS files while in CKEditor5 we use PostCSS. The config you provided should affect PostCSS files only.

> Error: Failed to find '~@/assets/slim_table.css'

It's a CSS file, not SCSS. Did it come from `assets/slim_table.scss`?

> my aliases in my sass files that map ~@ to src/ break.

What these aliases look like?

**Comment by agronick** [comment]
Its being included from sass as @import '~@/assets/slim_table.css'. For some reason postcss is involved with this in a default Vue setup even for sass files. Vue provides the ~@ alias by default.

I made some progress by shifting the resolve plugin off the config array. I was able to get it to build and render but the theme would not load.

**Comment by ma2ciek** [comment]
> Vue provides the ~@ alias by default.

Oh, didn't know that. @oleq, who is an owner of this integration is unfortunately off now, I'll try to help you during his absence.

> I made some progress by shifting the resolve plugin off the config array. I was able to get it to build and render but the theme would not load.

Could you share your results? I guess that it should be possible to somehow restrict the loader to parse only given files. Unfortunately, I don't know how it can be achieved with Vue way of creating webpack dynamically like here: https://cli.vuejs.org/guide/css.html#passing-options-to-pre-processor-loaders. But maybe it's possible with the [`chainWebpack`](https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-loader) and `.test(/\node_modules\/@ckeditor/)` or some similar regexp to match only CKEditor5 PostCSS files that  should be transpiled by `postcss-loader`.

**Comment by agronick** [comment]
Yeah, when I get to work I'll throw something together. Im pretty sure Vue has it's own resolve method thats being overridden.

**Comment by agronick** [comment]
Ok so I put together an example project. 
https://github.com/agronick/ckeditor-import-example

Oddly enough it worked at first. I've narrowed the bug down. It seems it breaks two things.

1. Importing CSS from SASS
2. Any URL in CSS with a relative import

You can see in HelloWorld.vue that it can't resolve `@import "~@/assets/something.css"`. But if you change that to @import "../assets/something.css" then it can't resolve `background-image: url('./logo.png')` in something.css. 

If you delete vue.config.js and change HelloWorld.vue to
```
<template>
    <div id="app">
    </div>
</template>

<script>

    export default {
    };
</script>

<style lang="sass">
@import "~@/assets/something.css"
</style>
```

The problem resolved. 

I was able to fix the bug by changing all of my CSS files to SASS in my main project. This isn't an optimal solution though.

**Comment by ma2ciek** [comment]
So the bug is pretty simple I guess. PostCSS loader parses your application files and can't resolve the `~@` imports. Have you tried the approach I asked you in the post above? To exclude src from files loaded by the `postcss-loader`?

**Comment by agronick** [comment]
You're a genius. That totally worked. You'll probably want to update the docs with something like this:
```
  chainWebpack: config => {
    config.module
      .rule('cke-css')
      .test(/(.*)ckeditor5-(.*).css/)
      .use('postcss-loader')
      .loader('postcss-loader')
      .tap(() => {
        return styles.getPostCssConfig({
          themeImporter: {
            themePath: require.resolve('@ckeditor/ckeditor5-theme-lark'),
          },
          minify: true,
        });
      });
     }
```

**Comment by agronick** [comment]
I made the changes for you in ckeditor5/1775.

**Comment by ma2ciek** [comment]
Glad you made it work.

And thanks for the PR 👍
Once the @oleq will be back we review it.

Cheers
