### ISSUE TITLE
Decoupled Document Editor

### ISSUE THREAD

**Issue by kl3sk** [ckeditor/ckeditor5-vue#6]
As I found a hacky solution (not the real one I think) in https://github.com/ckeditor/ckeditor5-vue/issues/5

I try with the decoupled document editor, but now nothing appears with no error.

The element (div in my case) won't be replaced with the editor.

**Comment by kl3sk** [comment]
I don't try other editors, but it could be the same.

**Comment by Reinmar** [comment]
We're thinking to document it similarly to how it's covered in the React component docs: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#note-using-the-document-editor-build. However, I didn't check yet whether that would work with the Vue.js component too.

**Comment by kl3sk** [comment]
I'am glad to read it when ready.

**Comment by oleq** [comment]
I checked and it works pretty much the same as React component. Just put `editor.ui.view.toolbar.element` anywhere you want. We should definitely include that in docs.

```js
<template>
	<div id="app">
		<ckeditor :editor="editor" v-model="editorData" :config="editorConfig" @ready="onReady"></ckeditor>
	</div>
</template>

<script>
	import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';
	
	export default {
		name: 'app',
		data() {
			return {
				editor: DecoupledEditor,
				editorData: '<p>Content of the editor.</p>',
				editorConfig: {
				}
			};
		},
		methods: {
			onReady( editor )  {
				document.body.prepend( editor.ui.view.toolbar.element );
			}
		}
	}
</script>
```

**Comment by oleq** [comment]
OTOH, I realised that we always pass the element to `Editor.create()` in the component so we're kinda missing the [last scenario](https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-decoupled_decouplededitor-DecoupledEditor.html#static-function-create) from the `DecoupledEditor.create()` where one can decide where to insert both the editable and the toolbar: 

```js
DecoupledEditor
    .create( '<p>Editor data</p>' )
    .then( editor => {
        // Append the toolbar to the <body> element.
        document.body.appendChild( editor.ui.view.toolbar.element );

        // Append the editable to the <body> element.
        document.body.appendChild( editor.ui.view.editable.element );

        console.log( 'Editor was initialized', editor );
    } )
    .catch( err => {
        console.error( err.stack );
    } );
```

OTTH I see that [react component docs](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#note-using-the-document-editor-build) suggest this let-me-handle-everything scenario is possible:

```js
                <CKEditor
                    onInit={ editor => {
                        console.log( 'Editor is ready to use!', editor );

                        // Insert the toolbar before the editable area.
                        editor.ui.view.editable.element.parentElement.insertBefore(
                            editor.ui.view.toolbar.element,
                            editor.ui.view.editable.element
                        );
                    } }

                    // ...
                />
```

despite the fact that we [pass the element to `create()` there too](https://github.com/ckeditor/ckeditor5-react/blob/master/src/ckeditor.jsx#L43). How's that working, @pomek?

What if the editor component is next to some other reactive content in DOM which changes a lot? How does react–controlled content interact with our toolbar and editable that we injected using native DOM methods (outside React)?

**Comment by pomek** [comment]
> How's that working, @pomek?

We pass always an HTML element because I had some troubles (that, of course, I don't remember now) when a content is passed to `Editor.create()` instead of the element. May it was related to the React component itself: when you have a code like : 

```html
<ckeditor ... />
```

you expect that in this place the editor will appear. If you pass the content, the editor won't appear and you must care about it when the editor is ready. So a code below:

```html
<ckeditor data="Test." .../>
```

would introduce confusing feelings – you defined a component with an initial data but the editor won't appear. 

> What if the editor component is next to some other reactive content in DOM which changes a lot?

I don't know. I've never tested such scenario.

**Comment by ma2ciek** [comment]
We've started when there was no option to pass data without element to the `Editor.create()` AFAIR.

**Comment by pomek** [comment]
`Editor.create( elementOrData )` was merged before we polished React integration. 

More about this problem – https://github.com/ckeditor/ckeditor5-core/issues/64.

**Comment by kl3sk** [comment]
I follow @oleq [steps](https://github.com/ckeditor/ckeditor5-vue/issues/6#issuecomment-436228102) like this:
```html
<template>
        <div ref="editorWrapper">
            <ckeditor
                    v-model="form.content"
                    :editor="editor"
                    :rules="rules.contentRules"
                    :config="editorConfig"
                    :disabled="loading"
                    @ready="onReady"
            ></ckeditor>
        </div>
</template>
```
```javascript
...
  methods: {
    onReady (editor) {
      this.$refs.editorWrapper.prepend(editor.ui.view.toolbar.element)
    }
}
...
```
Here is my result
![image](https://user-images.githubusercontent.com/2953145/48067492-b91e0680-e1d0-11e8-8d2c-4ed31ee58f4b.png)


But not styles applied.

**Comment by oleq** [comment]
> But not styles applied.

Which styles? Of the editor UI? Of the content?

**Comment by kl3sk** [comment]
I finally found a way.

I use the structure and the styles gave in the [documentation](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/document-editor.html).

**Comment by oleq** [comment]
Since the feature is working, I think we should limit our actions to the corresponding documentation.

**Comment by oleq** [comment]
@matamune94 What problem do you have?

**Comment by oleq** [comment]
Just to let you know, we added a new section to the Vue.js integration guide in our docs. It will be published online soon.
