### ISSUE TITLE
how to set character limit from vue component?

### ISSUE THREAD

**Issue by sameerkarmacharya** [ckeditor/ckeditor5-vue#63]

**Comment by Mgsy** [comment]
Hi, can you write more about your problem? What exactly do you want to achieve?

**Comment by sameerkarmacharya** [comment]
Hello,
I am trying to limit character in ck editor 5 using vue component and I
couldn't apply character limit.

**Comment by Mgsy** [comment]
Currently, CKEditor 5 doesn't have such a feature, but we've started working on Word count plugin.  You can read the [discussion](https://github.com/ckeditor/ckeditor5/issues/1301) and check out the [specification](https://github.com/ckeditor/ckeditor5-word-count/issues/1) (as you can see, there is a plan for adding support for limits, but not in the first implementation).

**Comment by laratutodotcom** [comment]
[Solution: is here verify your config [file]](https://laratuto.com/how-to-set-character-limit-in-ckeditor-5)
