### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by tanakaworld** [ckeditor/ckeditor5-vue#67]
I got this error in ckeditor.js on runtime when I only import `'@ckeditor/ckeditor5-build-classic'`.
How should I solve this?

![image](https://user-images.githubusercontent.com/3489430/58965107-fab87380-87ea-11e9-8813-be1682bd2e99.png)

`package.json`

```
"@ckeditor/ckeditor5-build-classic": "^12.2.0",
"@ckeditor/ckeditor5-vue": "^1.0.0-beta.2",
```

`.babelrc`

```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false,
        "forceAllTransforms": true,
        "useBuiltIns": "entry"
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-transform-destructuring",
    "@babel/plugin-syntax-dynamic-import",
    [
      "@babel/plugin-proposal-object-rest-spread",
      {
        "useBuiltIns": true
      }
    ],
    [
      "@babel/plugin-transform-runtime",
      {
        "helpers": false,
        "regenerator": true
      }
    ],
    [
      "@babel/plugin-transform-regenerator",
      {
        "async": false
      }
    ],
    [
      "@babel/plugin-proposal-class-properties",
      {
        "loose": true
      }
    ]
  ]
}
```

**Comment by tanakaworld** [comment]
I added explicitly loading `regenerator-runtime` at first in entry point and solved it.

```
import 'regenerator-runtime'
```

Though this seems monkey patch, it temporary works fine.

**Comment by varunwilson6** [comment]
Hi,


> I added explicitly loading `regenerator-runtime` at first in entry point and solved it.
> 
> ```
> import 'regenerator-runtime'
> ```
> 
> Though this seems monkey patch, it temporary works fine.

Hi, First entry point means, can you please specify
