### ISSUE TITLE
Vue.use options

### ISSUE THREAD

**Issue by kl3sk** [ckeditor/ckeditor5-vue#7]
As described in the [work in progress VueJs implementation doc](https://github.com/ckeditor/ckeditor5/blob/5e017e614ac0ad1faa243df6fd6b46efce38364c/docs/builds/guides/frameworks/vuejs.md).

The initialisation of Vue plugin use options like these 
```javascript
Vue.use( CKEditor, {
	editors: {
		classic: ClassicEditor
	}
} );
```

What is the purpose of the object `editors`, is it to  be able to load multiple Editor to use later ?
If it is, it raise a `version confilct error`.

If it is not planned to used as this, it could be a great feature.

Again thanks for all your work.

**Comment by Reinmar** [comment]
I've been now reviewing the component docs and it caught my attention as well. I think that it'd be just easier if you'd do it like:

```html
<template>
	<div id="app">
		<ckeditor :editor="editorConstructor" ... ></ckeditor>
	</div>
</template>

<script>
	export default {
		name: 'app',
		data() {
			return {
				editorConstructor: ClassicEditor,

				// ...
			};
		}
	}
</script>
```

WDYT?
