### ISSUE TITLE
Errors after following 'using CKEditor from source' guide

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-vue#70]
After following the [using CKEditor from source guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source), there are errors on init:

```
log.js?fb59:57 plugincollection-load: It was not possible to load the plugin. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-plugincollection-load
 {plugin: ƒ}

ckeditor.js?3730:5 CKEditorError: plugincollection-plugin-not-loaded: The requested plugin is not loaded. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-plugincollection-plugin-not-loaded
 {"plugin":"ContextualBalloon"}
    at PluginCollection.get (webpack-internal:///./node_modules/@ckeditor/ckeditor5-core/src/plugincollection.js:266:15)
    at LinkUI.init (webpack-internal:///./node_modules/@ckeditor/ckeditor5-link/src/linkui.js:87:48)

iconview.js?b512:122 Uncaught (in promise) TypeError: Cannot read property 'getAttribute' of null
    at IconView._updateXMLContent (iconview.js?b512:122)
    at IconView.render (iconview.js?b512:95)
    at IconView.eval (observablemixin.js?3466:263)
    at IconView.fire (emittermixin.js?e4c7:236)
    at IconView.<computed> [as render] (observablemixin.js?3466:271)
    at ViewCollection.eval (viewcollection.js?5a1d:81)
    at ViewCollection.fire (emittermixin.js?e4c7:236)
    at ViewCollection.add (collection.js?7731:178)
    at ButtonView.render (buttonview.js?d175:191)
    at ButtonView.eval (observablemixin.js?3466:263)
```

Uncommenting this part from the `vue.config.js` file solves the problem:
```js
svgRule.uses.clear();
```

cc @oleq

**Comment by oleq** [comment]
Today I revisited this section of the guide when working on https://github.com/ckeditor/ckeditor5/commit/dd5aa844236bba624fa01e73d6aa8e6ea680898e (related to CSS not SVG). I created an environment from scratch and followed the instructions 1:1 and it worked for me out-of-the-box. Can you pull the latest documentation and check this out again?

**Comment by Mgsy** [comment]
Unfortunately, I'm still able to reproduce it. From time to time we receive reports about this problem, i.e. - https://github.com/ckeditor/ckeditor5-vue/issues/69, https://github.com/ckeditor/ckeditor5/issues/1735.

I'm building the editor on Windows, so maybe it's a problem related to this platform 🤔 I'll check whether I can reproduce it on Linux.

**Comment by Mgsy** [comment]
So, I've repeated the test on Linux and it works fine. It looks like this issue occurs only on Windows.

**Comment by oleq** [comment]
@Mgsy: if your webpack config on Windows has the following line 

```
svgRule.exclude.add( __dirname + '/node_modules/@ckeditor' );
```

can you replace it with

```
const path = require( 'path' );

// ...

svgRule.exclude.add( path.join( __dirname, 'node_modules', '@ckeditor' ) );
```

and see of that helps?

**Comment by Mgsy** [comment]
Yay! It solves the problem 🎉
