### ISSUE TITLE
[Docs] Missing dependency in snippet

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-vue#73]
The snippet in https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-the-editor-from-source is missing a `@ckeditor/ckeditor5-theme-lark` dependency, so it throws after running `npm run build`.

**Comment by mlewand** [comment]
Duplicate of a issue (with a very poor title though 😂) ckeditor/ckeditor5#1412.
