### ISSUE TITLE
[Nuxt.JS + Vuetify] Error after import 'CKEditor5' (window is not defined )

### ISSUE THREAD

**Issue by migaduo** [ckeditor/ckeditor5-vue#74]
Hey @all,

i get the following Error after put this in my VueJS Application:

'window is not defined'

```
import CKEditor from '@ckeditor/ckeditor5-vue';

components: {
      ckeditor: CKEditor.component
    },
```

Did someone know how to fix it?

I'm using "Nuxt.JS/VueJS/Vuetify"

Thanks for the support!

**Comment by Mgsy** [comment]
Hello, did you follow our [Vue.js integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html)?

**Comment by migaduo** [comment]
Yeah, i tried all implementations. :(

**Comment by Mgsy** [comment]
Okay, so can you provide exact steps which you perform, so we'll be able to reproduce your issue? Also, all the details about your environment will be appreciated.

**Comment by pomek** [comment]
Most probably the issue is related to SSR. If so, there is a related issue – https://github.com/ckeditor/ckeditor5/issues/1511.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.

**Comment by AbbasHasani** [comment]
you should use this condition to load plugin in client mode

if (process.client) {
    CKEditor = require('@ckeditor/ckeditor5-vue')

    Vue.use(CKEditor);
}

**Comment by usb248** [comment]
There is any support for SSR for ckeditor, That's why it displays error : window is not defined.
The only clean solution is to use https://nuxtjs.org/guide/plugins#client-side-only but it induces to use it in a global way ... :-1:

**Comment by anurag-do** [comment]
@usb248 its working thanks. 
was searching for 4 hours.

finally got this worked.

page.vue

```
<template>
  <div id="app">
    <ckeditor :editor="editor" v-model="editorData" :config="editorConfig"></ckeditor>
  </div>
</template>

<script>
  let ClassicEditor
  let CKEditor

  if (process.client) {
    ClassicEditor = require('@ckeditor/ckeditor5-build-classic')
    CKEditor = require('@ckeditor/ckeditor5-vue')
  } else {
    CKEditor = { component : {template:'<div></div>'}}
  }

  export default {
    components : { 
      ckeditor: CKEditor.component
    },
    data() {
      return {
          editor: ClassicEditor,
          editorData: '<p>Content of the editor.</p>',
          editorConfig: {
              // The configuration of the editor.
          }
      };
    }
  }
</script>
```

**Comment by metrey** [comment]
The solution at https://github.com/ckeditor/ckeditor5-vue/issues/74#issuecomment-589584106 worked!

**Comment by kaplanark** [comment]
Unfortunately, I couldn't do what you said in the Nuxt3 version. Could you guide me in this matter?

**Comment by m2sahin** [comment]
Problem still persists for Nuxt 3

**Comment by 9uenther** [comment]
I use it this way

```vue
<template>
    <client-only>
        <CKEditor 
            v-if="ClassicEditor" 
            v-model="content"
            :editor="ClassicEditor"
        ></CKEditor>
    </client-only>
</template>
<script setup>
    let CKEditor
    let ClassicEditor = ref()

    if (process.client) {
        CKEditor = defineAsyncComponent(() => import('@ckeditor/ckeditor5-vue').then(module => module.component))
        import('@ckeditor/ckeditor5-build-classic').then(e => ClassicEditor.value = e.default)
    }
</script
```

**Comment by N-index** [comment]
> I use it this way

Doing it this way will render SSR meaningless

**Comment by N-index** [comment]
> I use it this way
> 
> ```
> <template>
>     <client-only>
>         <CKEditor 
>             v-if="ClassicEditor" 
>             v-model="content"
>             :editor="ClassicEditor"
>         ></CKEditor>
>     </client-only>
> </template>
> <script setup>
>     let CKEditor
>     let ClassicEditor = ref()
> 
>     if (process.client) {
>         CKEditor = defineAsyncComponent(() => import('@ckeditor/ckeditor5-vue').then(module => module.component))
>         import('@ckeditor/ckeditor5-build-classic').then(e => ClassicEditor.value = e.default)
>     }
> </script
> ```

Doing it this way will make SSR meaningless
