### ISSUE TITLE
Styles can't be brought to the front desk

### ISSUE THREAD

**Issue by wo642436249** [ckeditor/ckeditor5-vue#76]
Publish a content in the background of a project using the editor, call the data in the front of the project, and find that the style is different from that in the editor.

在项目的后台使用该编辑器发布一篇内容，在项目的前台调用该数据，发现样式和编辑器中的样式不同

**Comment by Mgsy** [comment]
Hello, can you describe your case more specific? Please provide steps you perform, expected and actual result.
