### ISSUE TITLE
How can I bind an entity property to the document editor editable area?

### ISSUE THREAD

**Issue by sebasijan** [ckeditor/ckeditor5-vue#77]
I have my document editor setup like this

    <div class="document-editor">
        <div class="document-editor__toolbar"></div>
        <div class="document-editor__editable-container">
            <div class="document-editor__editable">
                
            </div>
        </div>
    </div>

as per [the docs](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/document-editor.html)

And I want to bind the user's input to some datamodel property. but I can't work out how to do it. 

I would have just used the default decoupled-document editor, but it looks nothing like the one created using the method above (which has nice margins). I tried assigning my model property to some data property and then sticking it in `document-editor__editabl` with `{{editorData}}`, but then the text shows up as markup rather than actually formatting it like a rich text editor!

**Comment by Mgsy** [comment]
Hi, can you show us the code, so it will be easier for us to look at your solution and investigate it?
