### ISSUE TITLE
CKEditor5 custom build problem Vue JS

### ISSUE THREAD

**Issue by 2gavy** [ckeditor/ckeditor5-vue#78]
Similar to #65. 

I'm building a custom CKEditor too.

I have installed the Vue dependencies properly, but still facing this error:

```
./node_modules/@ckeditor/ckeditor5-engine/src/view/element.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: path.hub.addHelper is not a function at PluginPass.NewExpress... at newFn ... at NodePath._call
```

Thanks for your help. :)

**Comment by Mgsy** [comment]
Hello, did you follow our [Vue.js integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html)?

**Comment by 2gavy** [comment]
Hi @Mgsy, I certainly did. Installed all the plugins as instructed...

**Comment by Mgsy** [comment]
Can you share your code? Your `package.json`, `vue.config.js` and component files will be much appreciated.
