### ISSUE TITLE
PasteFromOffice plugin doesn't seem to work with ckeditor5-vue

### ISSUE THREAD

**Issue by Loremaster** [ckeditor/ckeditor5-vue#79]
Hey,

Hope it's correct place to report the issue. I am trying to enable [PasteFromOffice](https://ckeditor.com/docs/ckeditor5/latest/features/paste-from-word.html) with ckeditor5-vue. I have few other plugins which I was able to install. Those ones work correct. However this one doesn't seem to work at all. Can you give any suggestions how to resolve it? 

Sample table is taken from here: https://ckeditor.com/docs/ckeditor5/latest/assets/CKEditor5.PFO.Sample.Recognition_of_Achievement.docx

After inserting it looks like that:

<img width="1426" alt="Screenshot at Jul 16 15-28-21" src="https://user-images.githubusercontent.com/1028215/61298380-632d4400-a7de-11e9-8290-e36a2028f85f.png">

My component looks like that:

```vue
<template>
  <div class="editor">
    <ckeditor :editor="editor" v-model="editorData" :config="editorConfig" />
  </div>
</template>

<script>
import ClassicEditor from "@ckeditor/ckeditor5-editor-classic/src/classiceditor";
import EssentialsPlugin from "@ckeditor/ckeditor5-essentials/src/essentials";
import BoldPlugin from "@ckeditor/ckeditor5-basic-styles/src/bold";
import ItalicPlugin from "@ckeditor/ckeditor5-basic-styles/src/italic";
import LinkPlugin from "@ckeditor/ckeditor5-link/src/link";
import ParagraphPlugin from "@ckeditor/ckeditor5-paragraph/src/paragraph";
import Font from "@ckeditor/ckeditor5-font/src/font";
import PasteFromOffice from "@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice";

export default {
  name: "Editor",
  data() {
    return {
      editor: ClassicEditor,
      editorData: "<p>Content of the editor.</p>",
      editorConfig: {
        plugins: [
          EssentialsPlugin,
          PasteFromOffice,
          BoldPlugin,
          ItalicPlugin,
          LinkPlugin,
          ParagraphPlugin,
          Font
        ],
        fontFamily: {
          options: [
            "Arial, Helvetica, sans-serif",
            "Ubuntu, Arial, sans-serif",
            "Ubuntu Mono, Courier New, Courier, monospace"
          ]
        },
        toolbar: {
          items: [
            "bold",
            "italic",
            "link",
            "undo",
            "redo",
            "fontSize",
            "fontFamily",
            "fontColor",
            "fontBackgroundColor"
          ]
        }
      }
    };
  }
};
</script>
```

Source code is here: https://github.com/Loremaster/ckeditor5-vue

**Comment by Mgsy** [comment]
This is interesting. I'm able to reproduce this problem while building the editor from the source. If I integrate a classic build, everything works fine 🤔 

cc @oleq

**Comment by Loremaster** [comment]
Any updates on this?

**Comment by oleq** [comment]
Does `editor.plugins.get( 'PasteFromOffice' )` return a plugin instance?

**Comment by Mgsy** [comment]
>Does editor.plugins.get( 'PasteFromOffice' ) return a plugin instance?

Yes, it does.

**Comment by oleq** [comment]
OK, I see what's wrong now. 

You imported the `ckeditor5-paste-from-office` plugin but you're missing other plugins like `ckeditor5-table`, `ckeditor5-list`, `ckeditor5-alignment` and so on. 

`ckeditor5-paste-from-office` is a sort of bridge between the Office and CKEditor. It translates the output from Office (Word) into something the editor can process. But to allow some kinds of content (tables, lists, text alignment), their respective features must also be loaded into the editor. Without them, even if the bridge works, the editor will discard the content it does not recognize (in [Schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html)).

Get some [more features](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) and your content should look way better. The more–or–less complete list is [here](https://ckeditor.com/docs/ckeditor5/latest/features/index.html).
