### ISSUE TITLE
Is there a way to access vue component data in custom plugin ?

### ISSUE THREAD

**Issue by KirankumarAmbati** [ckeditor/ckeditor5-vue#80]
I have tried 2 approaches to create custom plugin. 

1. To create a class MyCustomPlugin and give it to extraPlugins property while creating CKEditor.
2. To create plugin in CKEditor source, add it to ClassicEditor.builtinPlugins, build it and use the build in my project.

MyCustomPlugin:

```
class AdditionalPluginsIntegration {
        constructor( editor ) {
            this.editor = editor;
        }

        init() {   
            const usersPlugin = this.editor.plugins.get( 'Users' );
            const commentsPlugin = this.editor.plugins.get( 'Comments' );
            const trackedChangesPlugin = this.editor.plugins.get( 'TrackChanges' );

            // Load the users data.
            for ( const user of appData.users ) {
                usersPlugin.addUser( user );
            }

            // Set the current user.
            usersPlugin.defineMe( appData.userId );

            // Load the comment threads data.
            for ( const commentThread of appData.commentThreads ) {
                commentsPlugin.addCommentThread( commentThread );
            }

            // Load the suggestion threads data.
            for ( const suggestionThread of appData.suggestionThreads ) {
                trackedChangesPlugin.addSuggestion( suggestionThread );
            }
        }
    }
```
In my customPlugin, how can I access my ```appData``` ( which I used in plugin ) ? appData is present in my Vue Component ```data``` field.

Urget help required! Thanks.

**Comment by KirankumarAmbati** [comment]
**CC:** @oleq; @Reinmar; @elszczepano;

**Comment by KirankumarAmbati** [comment]
Thanks for the response!

Sorry if my question conveyed wrongly. Actually I have written a separate component to render the CKEditor. 

```
<template>
    <div class="editor-container">
        <div :id="`editor-${model}${index !== undefined ? index : ''}`"></div>
        <div :id="`sidebar-${model}${index !== undefined ? index : ''}`" class="editor-sidebar"></div>
    </div>
</template>
<script>
    ...
    export default {
        data() {
            ....
            return {
                appData // This data has commentThreads, suggestionThreads, users, userID
            }
        },
        mounted() {
            this.initializeEditor()
        },
        methods: {
            initializeEditor() {
                ClassicEditor
                    .create( document.querySelector( `#editor-${this.model}${this.index !== undefined ? this.index : ''}` ), {
                        initialData: this.appData.initialData,
                        extraPlugins: [ AdditionalPluginsIntegration ],
                        licenseKey: 'MY_LICENSE_KEY',
                        sidebar: {
                            container: document.querySelector( `#sidebar-${this.model}${this.index !== undefined ? this.index : ''}` )
                        },
                        toolbar: {
                            items: ['bold','italic','link','bulletedList','numberedList','undo','redo','comment','trackChanges']
                        }
                    } )
                    .then( editor => {
                        const comments = editor.plugins.get( 'Comments' );
                        const trackedChangesPlugin = editor.plugins.get('TrackChanges');

                        ...
                        const editorData = editor.data.get();
                        const commentThreadsData = Array.from( comments.getCommentThreads() );
                        const trackedChanges = Array.from(trackedChangesPlugin.getSuggestions());
                        ....                                    
            }
        }
    }

    class AdditionalPluginsIntegration {
        constructor( editor ) {
            this.editor = editor;
        }

        init() {           
            const usersPlugin = this.editor.plugins.get( 'Users' );
            const commentsPlugin = this.editor.plugins.get( 'Comments' );
            const trackedChangesPlugin = this.editor.plugins.get( 'TrackChanges' );

            // Load the users data.
            for ( const user of appData.users ) {
                usersPlugin.addUser( user );
            }

            // Set the current user.
            usersPlugin.defineMe( appData.userId );

            // Load the comment threads data.
            for ( const commentThread of appData.commentThreads ) {
                commentsPlugin.addCommentThread( commentThread );
            }

            // Load the suggestion threads data.
            for ( const suggestionThread of appData.suggestionThreads ) {
                trackedChangesPlugin.addSuggestion( suggestionThread );
            }
        }
    }
</script>
```

I'm trying to access appData from component data in my custom plugin. Both are present in the same file. I have created separate component to have Editor with Sidebar( to display comments and tracked changes ) and to implement custom plugin. 

Please can you confirm if my approach of creating a CKEditor component correct ? 

I'm going to have >5 CKEditors on my page.  All are from above component.

**Note:** I'm not able to find more info for Vue hence asking this here. Thanks for understanding!

**Comment by KirankumarAmbati** [comment]
As per the CKEditor5 docs:

https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/comments/comments-integration.html#full-implementation

It is mentioned that the appData (containing users, userId, commentThreads) is to be declared as Global variable and used it in assigning the values to Editor plugins. How to approach the scenario if I have to render many (say 4) CKEditors on my screen. I am unable to follow the same approach in my Vue component since the appData declared on top of the component is acting as a Global Variable and is taking the values of the last CKEditor for all 4 CKEditors and CKEditor is trying to assign that values to all CKEditor plugins, which is unexpected. 

Help required with this.

Please correct me if my understanding is wrong. Thanks!

**Comment by KirankumarAmbati** [comment]
**One more approach:**

I tried the below approach as well, but it didnt work.

```
ClassicEditor
.create( document.querySelector( `#editor-${this.model}${this.index !== undefined ? this.index : ''}` ), {
          ...
         } )
         .then( editor => {                       
             this.setCommentsAndSuggestions(editor, this.appData);
             ...
          })
```
**setCommentsAndSuggestions** is written as method in Vue component as below:

```
setCommentsAndSuggestions(editor, appData) {
                
                const usersPlugin = editor.plugins.get( 'Users' );
                const commentsPlugin = editor.plugins.get( 'Comments' );
                const trackedChangesPlugin = editor.plugins.get( 'TrackChanges' );

                // Load the users data.
                for ( const user of appData.users ) {
                    usersPlugin.addUser( user );
                }

                // Set the current user.
                usersPlugin.defineMe( appData.userId );

                // Load the comment threads data.
                for ( const commentThread of appData.commentThreads ) {
                    console.log('THRED: ', commentThread);
                    
                    commentsPlugin.addCommentThread( commentThread );
                }

                // Load the suggestion threads data.
                for ( const suggestionThread of appData.suggestionThreads ) {
                    trackedChangesPlugin.addSuggestion( suggestionThread );
                }
            }
```

I'm seeing the below errors:

![image](https://user-images.githubusercontent.com/9110567/61637202-beff3d80-acb4-11e9-9b8b-42e4e4dcc79b.png)

![image](https://user-images.githubusercontent.com/9110567/61637256-d3433a80-acb4-11e9-9df8-cb579de0fa60.png)

**Comment by oleq** [comment]
> Sorry if my question conveyed wrongly. Actually I have written a separate component to render the CKEditor.

This issue tracker is for the official CKEditor 5 component for Vue.js. This issue doesn't concern the official component but a custom 3rd–party software and I'm afraid I won't be able to assist you. 

There are other ways of [getting support](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/support/getting-support.html) you can consider.

**Comment by KirankumarAmbati** [comment]
One small question: Are tracked changes plugin and comments plugin belongs to third-party ? ( My thinking was that they are new features integrated into CKEditor-5 )
Thanks!

**Comment by Mgsy** [comment]
>Are tracked changes plugin and comments plugin belongs to third-party ? ( My thinking was that they are new features integrated into CKEditor-5 )

Track Changes and Comments plugins belong to CKEditor 5, but are commercial plugins. If you'd like to hear more about them, please [contact us](https://ckeditor.com/contact/) and our team will be happy to answer all your questions.

**Comment by Mgsy** [comment]
@KirankumarAmbati, I'd like to apologize, because we didn't understand your case correctly and we treated it as Vue-related problem, but it's an issue with the integration of track changes and comments. 

This issue tracker is dedicated to an open-source part of our project, as track changes and comments are commercials plugins, all problems should be reported through our support channel. Please, send a message to support@cksource.com with a detailed description of your problem. Thank you!

**Comment by KirankumarAmbati** [comment]
Thanks @Mgsy!
