### ISSUE TITLE
Language option on config not working

### ISSUE THREAD

**Issue by gabrielsclimaco** [ckeditor/ckeditor5-vue#84]
I set up a language option on the editor config, but the editor it's still in english

the code:
```html
<ckeditor v-model="news.body" :editor="editor" :config="editorCofig"></ckeditor>
```
```js
  data: () => ({
    editor: ClassicEditor,
    editorCofig: {
      language: 'pt',
    },
  })
```

the result:
![image](https://user-images.githubusercontent.com/8144779/61839135-c2d0c280-ae62-11e9-9d51-9eecb7311b8e.png)

**Comment by Mgsy** [comment]
Hello, the language of your UI doesn't change, because you didn't import your language. By default, CKEditor 5 uses English. Just add this import and everything should work fine:

```js
import '@ckeditor/ckeditor5-build-classic/build/translations/pt';
```

**Comment by ma2ciek** [comment]
Not sure if it's stated in Vue's docs, cc @oleq.

**Comment by oleq** [comment]
Added a section to the guide. 

@gabrielsclimaco: check out my commit with the [updated guide](https://github.com/ckeditor/ckeditor5/commit/c5abda844cc670c5bfc68ee7e75fa78169002af8?short_path=0acf7b6#diff-0acf7b6d2c9b5050039b3d5741919a61) to solve your issue ASAP. The documentations should also should show up on https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html soon.
