### ISSUE TITLE
Could not find a declaration file for module '@ckeditor/ckeditor5-vue'

### ISSUE THREAD

**Issue by erickAvSanti** [ckeditor/ckeditor5-vue#85]
94:22 Could not find a declaration file for module '@ckeditor/ckeditor5-vue'. '/home/erick/git-projects/saps-vue/node_modules/@ckeditor/ckeditor5-vue/dist/ckeditor.js' implicitly has an 'any' type.
  Try `npm install @types/ckeditor__ckeditor5-vue` if it exists or add a new declaration (.d.ts) file containing `declare module '@ckeditor/ckeditor5-vue';`
    92 | 
    93 | 
  > 94 | import CKEditor from '@ckeditor/ckeditor5-vue';
       |                      ^
    95 | Vue.use( CKEditor );
    96 | 
    97 | new Vue({
Version: typescript 3.5.2

**Comment by ma2ciek** [comment]
Hi, @erickAvSanti 

The typings for this libs don't exist. if you use the `strict mode` in TypeScript you can follow the above instructions and create a declaration file for libs which miss typings.

The umbrella ticket: https://github.com/ckeditor/ckeditor5/issues/504.

**Comment by juanaguillon** [comment]
I've used shims-vue.d.ts (Vue3) declaration file (.d.ts) and put:
`declare module '@ckeditor/ckeditor5-vue';`
