### ISSUE TITLE
My styles has been removed

### ISSUE THREAD

**Issue by Uysim** [ckeditor/ckeditor5-vue#86]
I have a content look like
```html
<p style="line-height: 18px; margin: 10px 0; text-align: center;font-size:14px;color:#ffffff;font-family:'Times New Roman',Helvetica,Arial,sans-serif">abc</p>
```

When it passed in to the ckeditor it only 
```html
<p style="text-align:center;">abc</p>
```

**Comment by Mgsy** [comment]
Hello, some values from a `style` attribute are stripped because they are not registered in the schema and don't have a proper conversion. Please, read about [CKEditor 5 architecture](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html) to get a better understanding of how it works. Also, take a look at [Schema guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html) and [Conversion API](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html).

**Comment by Uysim** [comment]
@Mgsy Is there anything simpler than this? I think read this look like I have to implement my own editor

**Comment by Mgsy** [comment]
>@Mgsy Is there anything simpler than this? I think read this look like I am implementing my own editor

Unfortunately not. CKEditor 5 has a custom data model and accepts only those elements and attributes which have been allowed in the schema. 

However, if it's important for you to keep all the `style` values on paragraphs, I've prepared you a simple plugin which will handle it. Please, see it below:

```js
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';

/**
 * Paragraph style sttribute support for the CKEditor 5.
 */
export default class ParagraphStyle extends Plugin {
	init() {
		const schema = this.editor.model.schema;
		const conversion = this.editor.conversion;

		// Register custom paragraphStyles (later converted to style) attribute for paragraph element
		schema.extend( 'paragraph', { allowAttributes: 'paragraphStyles' } );				
	
		// Add an upacast (view-to-model) converter for style attribute of a paragraph.
		conversion.for( 'upcast' ).attributeToAttribute( {
			model: {
				name: 'paragraph',
				key: 'paragraphStyles',
				value: viewElement => viewElement.getAttribute( 'style' )
			},
			view: {
				name: 'p',
				key: 'style',
				value: /[\s\S]+/
			}
		} );

		// Add an downcast (model-to-view) converter for style attribute of a paragraph.
		// Workaround for https://github.com/ckeditor/ckeditor5-engine/issues/1740
		conversion.for( 'downcast' ).add( dispatcher => {
			dispatcher.on( 'attribute:paragraphStyles:paragraph', ( evt, data, conversionApi ) => {
				const viewElement = conversionApi.mapper.toViewElement( data.item );

				conversionApi.writer.setAttribute( 'style', data.attributeNewValue, viewElement );
			} );
		} );	
	}
}

```

Import it to the editor and rebuild it. In case of any problems, see our [Installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html).

**Comment by Uysim** [comment]
Thank @Mgsy. It work like charm
