### ISSUE TITLE
Using classic build in Nuxt, Link doesn’t save

### ISSUE THREAD

**Issue by carlmjohnson** [ckeditor/ckeditor5-vue#87]
I got CKEditor to show up and even v-model my data etc in Nuxt by mounting it only client side as an async component. The problem I am having is that the Link plugin doesn’t apply changes and create a link when I click the checkmark in the popup. Any ideas? Isn’t this plugin part of the classic build?

**Comment by carlmjohnson** [comment]
Containing page:

```
  components: {
    CKEditorField: () => import("~/components/CKEditorField.vue"),
  },
```

CKEditorField component:

```vue
<script>
import CKEditor from "@ckeditor/ckeditor5-vue";
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";

export default {
  components: {
    CKEditor: CKEditor.component
  },
  props: {
    value: String,
    label: String,
    help: String,
    validator: String
  },
  data() {
    return {
      content: this.value,
      editor: ClassicEditor,
      editorConfig: {
        toolbar: {
          items: ["bold", "italic", "link", "undo", "redo"]
        }
      }
    };
  },
  watch: {
    content(newVal) {
      this.$emit("input", newVal);
    }
  }
};
</script>

<template>
  <div class="field">
    <label class="label" v-text="label"></label>
    <div class="control">
      <CKEditor
        v-model="content"
        class="input"
        :editor="editor"
        :config="editorConfig"
      ></CKEditor>
      <p v-if="help" class="help" v-text="help"></p>
      <p v-if="validator" class="help is-danger" v-text="validator"></p>
    </div>
  </div>
</template>
```

Result:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/222245/62863795-db9cfd00-bcd7-11e9-80d4-f8d61710e85a.png">

When I hit the green check to save, nothing happens. The red X does close the pop over, but nothing will make the link save.

**Comment by carlmjohnson** [comment]
Huh, I've been developing in FireFox, and the link doesn't work, but I tried it in Safari and it does. Is this a browser bug in CKEditor?

My Yarn.lockfile versions:

"@ckeditor/ckeditor5-build-classic@^12.3.1":
  version "12.3.1"
  resolved "https://registry.yarnpkg.com/@ckeditor/ckeditor5-build-classic/-/ckeditor5-build-classic-12.3.1.tgz#b37011d5ee2f2590cf8d29a43dc5c62f14cf0b5a"
  integrity sha512-nlE8wRasM3AF2XkXHJuj91cq46ZvmTBfXePCtjogT8s/niYlFma+Lqu7cAUONxRXh11m1IpgC6i+QOGFZH0p8A==

"@ckeditor/ckeditor5-core@^12.2.1":
  version "12.2.1"
  resolved "https://registry.yarnpkg.com/@ckeditor/ckeditor5-core/-/ckeditor5-core-12.2.1.tgz#53fe65c57309fb2ed5828c8e67a5980532b7e50a"
  integrity sha512-1z6t56Evo3u/c11t4xSvxGdN/UB+UJ2PxzbiDf7ul0zBo/CE3Q3dYFjVRSKLKePhQOI1wti4sXCeLQaflh76VQ==
  dependencies:
    "@ckeditor/ckeditor5-engine" "^13.2.1"
    "@ckeditor/ckeditor5-utils" "^13.0.1"
    lodash-es "^4.17.10"

"@ckeditor/ckeditor5-editor-classic@^12.1.3":
  version "12.1.3"
  resolved "https://registry.yarnpkg.com/@ckeditor/ckeditor5-editor-classic/-/ckeditor5-editor-classic-12.1.3.tgz#9fe43ed84ddefb154be9ed21f935d6f165f6f5d5"
  integrity sha512-4uihbXT44+sdx+oCVLbjnlpHvU1oiW+9b+2AJJMWJQ0mb+s8SylM6pyV44CQnuo5xLV+vaKbVav8XeaN55QyCg==
  dependencies:
    "@ckeditor/ckeditor5-core" "^12.2.1"
    "@ckeditor/ckeditor5-engine" "^13.2.1"
    "@ckeditor/ckeditor5-ui" "^13.0.2"
    "@ckeditor/ckeditor5-utils" "^13.0.1"
    lodash-es "^4.17.10"

"@ckeditor/ckeditor5-engine@^13.2.1":
  version "13.2.1"
  resolved "https://registry.yarnpkg.com/@ckeditor/ckeditor5-engine/-/ckeditor5-engine-13.2.1.tgz#95941d6a4a53636e17533727837d439a8e3eb7c1"
  integrity sha512-yGERQGIYZwJtShi+CYuAWV5P1bvLDlMTMjHf+qPKCwXAw9RiWmjuS5MVpeaZRtmAMEGXyol+mf8IvYvXczfo8A==
  dependencies:
    "@ckeditor/ckeditor5-utils" "^13.0.1"
    lodash-es "^4.17.10"

"@ckeditor/ckeditor5-ui@^13.0.2":
  version "13.0.2"
  resolved "https://registry.yarnpkg.com/@ckeditor/ckeditor5-ui/-/ckeditor5-ui-13.0.2.tgz#99978d89ff5a5adbd28ac6586477501ac2db266a"
  integrity sha512-A2Ut+W3rHWNUNR1TwjdBQShl7v270hRlcz3Z77ka/0xlhkQ7TIAVlVHu8q89170fFE4Po8cSqGDZVO9YT3W75A==
  dependencies:
    "@ckeditor/ckeditor5-core" "^12.2.1"
    "@ckeditor/ckeditor5-utils" "^13.0.1"
    lodash-es "^4.17.10"

"@ckeditor/ckeditor5-utils@^13.0.1":
  version "13.0.1"
  resolved "https://registry.yarnpkg.com/@ckeditor/ckeditor5-utils/-/ckeditor5-utils-13.0.1.tgz#fc51c8d2e661d6ccd05748c1c53f1975835e1cbd"
  integrity sha512-u/18fD/lPeoir3R6+chBlm2ZCdvbqXqbx4yelOc4J+wzQUj53n0ZuADZrxXH0lXY/jsU5Lat0wisgmjwOkmGBw==
  dependencies:
    ckeditor5 "^12.3.1"
    lodash-es "^4.17.10"

"@ckeditor/ckeditor5-vue@^1.0.0-beta.2":
  version "1.0.0-beta.2"
  resolved "https://registry.yarnpkg.com/@ckeditor/ckeditor5-vue/-/ckeditor5-vue-1.0.0-beta.2.tgz#9491cf3e4b030847cd329ae3680c52996195d8bf"
  integrity sha512-9qF795EKQZi2VV5zgYjUfAY2L3rr50NaZOAMq2O2sADrWMxUGOb3cUAD6FuV3kboVaKoSmXGcApm7Iy5YTGr3g==

**Comment by Mgsy** [comment]
cc @oleq

**Comment by oleq** [comment]
Do typing and other features (list, tables, etc.) work for you?

**Comment by carlmjohnson** [comment]
Yes, everything else works: typing, bold, italics, blockquotes, tables, lists…

**Comment by oleq** [comment]
A weird question but I have to ask it anyway: are you 100% sure the link does not get inserted? Maybe CSS overrides its styles and it looks like plain text but it is inserted after all.

**Comment by carlmjohnson** [comment]
No, the clicking button doesn't cause the popup to close, and the HTML stays the same. If I add a link in Safari and then go back to Firefox, the link is visibly styled.

**Comment by oleq** [comment]
No errors in the console?

**Comment by carlmjohnson** [comment]
Nothing in console.

**Comment by Mgsy** [comment]
Hi @carlmjohnson, it's hard to find a source of the problem without seeing code and the actual behaviour. Are you able to create some live example with a minimal amount of code necessary to reproduce the issue?

**Comment by carlmjohnson** [comment]
I posted the component and the yarn file above. I can try to make a codepen or something later. Not sure what services will let me share a Nuxt project.

**Comment by Mgsy** [comment]
We've decided to open a separate [feature request](https://github.com/ckeditor/ckeditor5/issues/6071) for Nuxt.js integration. Feel free to add 👍 to the first post to bump its popularity and join the discussion.
