### ISSUE TITLE
Doesn't work at expected when edit a v-model

### ISSUE THREAD

**Issue by Jimmylet** [ckeditor/ckeditor5-vue#88]
Hello,

I integrated this plugin into my project. It works well except on one point.

When I edit on existing content, when I click on an element of the toolbar, it returns to the beginning of the document. It's the same with all the other elements of my toolbar.

Bolding, etc. works with keyboard commands. But not at the click.

But when I create a new element, everything works normally

```
data() {
      return {
        editItemForm: new Form({
          'question': this.item.question,
          'type': this.item.type
        }),
        visible: false,

        editor: ClassicEditor,
        editorConfig: {
          toolbar: {
            items: [
              'heading',
              'bold',
              'italic',
	      'bulletedlist',
	      'NumberedList',
              'link',
              'undo',
              'redo',
              'about'
         	],
          },
        }
      }
    }
```

```
<ckeditor :editor="editor" v-model="editItemForm.question" :config="editorConfig"></ckeditor>
```

Thank you!

**Comment by Jimmylet** [comment]
Any news ?

**Comment by Mgsy** [comment]
Hello, as I can see you use some custom plugin. Can you prepare some live demo and a code sample, so we'll be able to investigate it?
