### ISSUE TITLE
CKFinder icon greyed out

### ISSUE THREAD

**Issue by svkmedia** [ckeditor/ckeditor5-vue#89]
I finally managed to make work CKEditor in my Vue/Laravel app. Now I'm trying to add CKfinder but no success. Icon is greyed out. 
Here is my component:
https://jsfiddle.net/pen40mfw/1/

When I visit /ckfinder/browser everything works ok...
What I am doing wrong?

**Comment by jodator** [comment]
You're setting the wrong CKFinder configuration. Please read [configuring CKFinder in CKEditor 5](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/ckfinder.html#configuration).

**Comment by svkmedia** [comment]
@jodator I followed documentation. What's wrong in my code?

**Comment by jodator** [comment]
```
                    CKFinder: {
                        uploadUrl: '/ckfinder/connector?command=QuickUpload&type=Files&responseType=json',
                        filebrowserBrowseUrl: '/ckfinder/browser',
                        filebrowserImageBrowseUrl: '/ckfinder/browser?type=Images',
                        filebrowserUploadUrl:'/ckfinder/connector?command=QuickUpload&type=Files',
                        filebrowserImageUploadUrl: '/ckfinder/connector?command=QuickUpload&type=Images'
```
1. There's no `CKFinder` configuration option - there's `ckfinder` (it's case sensitive).
2. There's no `ckfinder.filebrowser*` configuration options - there's only [`ckfinder.uploadUrl`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ckfinder_ckfinder-CKFinderConfig.html#member-uploadUrl).
3. All [options for CKFinder](https://ckeditor.com/docs/ckfinder/ckfinder3/#!/api/CKFinder.Config) should go to [`ckfinder.options`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ckfinder_ckfinder-CKFinderConfig.html#member-options).

**Comment by svkmedia** [comment]
@jodator followed your steps but still CKFinder icon is greyed out...

**Comment by jodator** [comment]
@svkmedia sorry, somehow I've missed that - you should add also the `Image` plugin to the build (it's missing now) right now it is preventing the `CKFinderCommand` from proper function.

**Comment by jodator** [comment]
ps.: The `ImageUpload` is also needed.

**Comment by svkmedia** [comment]
@jodator thank you a lot! You saved my day
