### ISSUE TITLE
why？ Configuration by document Report errors ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more

### ISSUE THREAD

**Issue by yixinagqingyuan** [ckeditor/ckeditor5-vue#92]
app.vue

```js
<template>
  <div id="app">
    <ckeditor :editor="editor" v-model="editorData" :config="editorConfig"></ckeditor>
  </div>
</template>

<script>
// ⚠️ NOTE: We don't use @ckeditor/ckeditor5-build-classic any more!
// Since we're building CKEditor from source, we use the source version of ClassicEditor.
import ClassicEditor from "@ckeditor/ckeditor5-editor-classic/src/classiceditor";

import EssentialsPlugin from "@ckeditor/ckeditor5-essentials/src/essentials";
import BoldPlugin from "@ckeditor/ckeditor5-basic-styles/src/bold";
import ItalicPlugin from "@ckeditor/ckeditor5-basic-styles/src/italic";
import LinkPlugin from "@ckeditor/ckeditor5-link/src/link";
import ParagraphPlugin from "@ckeditor/ckeditor5-paragraph/src/paragraph";
//import RemoveFormat from '@ckeditor/ckeditor5-remove-format/src/removeformat';
//import WordCount from "@ckeditor/ckeditor5-word-count/src/wordcount";
import Highlight from '@ckeditor/ckeditor5-highlight/src/highlight';
export default {
  name: "app",
  data() {
    return {
      editor: ClassicEditor,
      editorData: "<p>Content of the editor.</p>",
      editorConfig: {
        plugins: [
          EssentialsPlugin,
          BoldPlugin,
          ItalicPlugin,
          LinkPlugin,
          ParagraphPlugin,
          Highlight
          //RemoveFormat
         // wordCount
        ],

        toolbar: {
          items: ["bold", "italic", "link", "undo", "redo",'Highlight']
        }
      }
    };
  }
};
</script>
```

**Comment by Mgsy** [comment]
Hello, did you follow our [Vue.js integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html)?

**Comment by yixinagqingyuan** [comment]
yes

**Comment by yixinagqingyuan** [comment]
Follow the document operation successfully，But I've added a plug-in to report an error，The added plug-in is  “Highlight”     
The referenced package is：
 import Highlight from '@ckeditor/ckeditor5-highlight/src/highlight'; 
And then it's wrong.
Answers    thanks

**Comment by Mgsy** [comment]
Please, make sure that your dependencies are updated. You can use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates), then reinstall all the packages if needed and see whether the issue still occurs.

**Comment by yixinagqingyuan** [comment]
Hello, it's completely documented. It's the latest thing, but it's still wrong.
Error reporting content：
Uncaught CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more:
Give a big guy an example.

**Comment by Mgsy** [comment]
Can you provide exact steps that you perform to reproduce this issue? I've just successfully created a custom build and integrated it with Vue, just by following our guide.

**Comment by yixinagqingyuan** [comment]
It's strange that I suddenly got better this morning. I can't find out why.thanks，but Block quote How to operate it and build it with source code，Please give me some guidance.

**Comment by yixinagqingyuan** [comment]
have already been solved，thanks
