### ISSUE TITLE
Media keeps reloading contents while editing with v-model

### ISSUE THREAD

**Issue by darylteo** [ckeditor/ckeditor5-vue#93]
```
 private editor = {
            build: BalloonEditor,
            config: {
                extraPlugins: [S3UploadAdapterPlugin],
                removePlugins: ['ImageCaption', 'ImageToolbar'],
                placeholder: 'Start writing your content...',

                blockToolbar: ['imageUpload', 'mediaEmbed', 'blockQuote', 'bulletedList', 'numberedList'],
                toolbar: ['bold', 'italic', 'blockQuote', 'bulletedList', 'numberedList', 'link', 'imageUpload'],

                image: {
                    toolbar: null,
                },

                mediaEmbed: {
                    previewsInData: true,
                },
            },
            methods: {}
        };

```

```
                    <ckeditor
                        :editor="editor.build"
                        :config="editor.config"

                        v-model="item.content"
                    ></ckeditor>
```

When inserting, say, a YouTube video, and continuing to type, the iframe content keeps refreshing repeatedly, which is not a good look to my client unfortunately.

I'm working around it by using a intermediary value that is saved to the store only when a save button is clicked, but it means it cannot be automatically persisted until user action.

If there's a workaround for this or if I've missed something, please let me know. Hopefully this is the right place as I don't believe it is a core ckeditor issue but rather to do with double binding. 

Regards,
Daryl

**Comment by Mgsy** [comment]
cc @oleq

**Comment by oleq** [comment]
I can't reproduce it in https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html. Is there anything more we should know about this issue?

**Comment by darylteo** [comment]
@oleq I believe it is related to the bidirectional binding used in frontend framework (in this case Vue). Doing it on a vanilla use case should not reproduce.

**Comment by oleq** [comment]
I also tested with Vue:

```html
<div id="app">
	<h1>CKEditor 5 – Vue.js Component – development sample</h1>

	<ckeditor
		editor="classic"
		tag-name="textarea"
		v-model="editorData"
		:editor="editor"
		:config="editorConfig"
	></ckeditor>

	<h2>Live editor data</h2>
	<textarea v-model="editorData"></textarea>
</div>

<script>
	Vue.use( CKEditor );

	const app = new Vue( {
		el: '#app',
		data: {
			editor: ClassicEditor,
			editorData: '<p>Hello world!</p><figure class="media"><oembed url="https://www.youtube.com/watch?v=H4p6njjPV_o"></oembed></figure>',
			editorConfig: { toolbar: [ 'heading', '|', 'bold', 'italic', 'mediaEmbed' ] },
		}
	} );
</script>
```
but to no avail.

**Comment by darylteo** [comment]
Good news and bad news!

---

# Bad news: 

https://codepen.io/darylteo/pen/xxKBEvq

This can be reproduced using BalloonEditor not ClassicEditor on 1.0.0-beta.2

# Good news: 

Updating to the new 1.0.0 release has resolved the issue, and the issue is no longer present, and I  will now seek to remove our hackarounds.

@oleq
