### ISSUE TITLE
Hello, how to set up "fileName" for uploading pictures

### ISSUE THREAD

**Issue by yixinagqingyuan** [ckeditor/ckeditor5-vue#96]
Backstage needs "fileName" to be another name，Seek guidance

**Comment by Mgsy** [comment]
Hi, can you describe your case more precisely? I'm not sure what do you want to achieve.

**Comment by yixinagqingyuan** [comment]
Picture upload field is upload I want to change it into one. file，

**Comment by yixinagqingyuan** [comment]
![1568618792307](https://user-images.githubusercontent.com/31228587/64940563-d9116280-d896-11e9-82a4-5473aa6736fe.jpg)
Picture upload field is upload I want to change it into one. file，

**Comment by yixinagqingyuan** [comment]
Sorry, English is not good. Chinese

**Comment by Mgsy** [comment]
I assume that you create your [own upload adapter](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html). So, you should change a parameter name in `_sendRequest()` method:

```js
_sendRequest( file ) {
        // Prepare the form data.
        const data = new FormData();

        data.append( 'upload', file ); // change 'upload' to your parameter name.

        // Important note: This is the right place to implement security mechanisms
        // like authentication and CSRF protection. For instance, you can use
        // XMLHttpRequest.setRequestHeader() to set the request headers containing
        // the CSRF token generated earlier by your application.

        // Send the request.
        this.xhr.send( data );
    }
```
