### ISSUE TITLE
Hello, I'm bothering you again. I uploaded the simpleuploadapter plug-in and took it outside to quote. Why did I report an error?

### ISSUE THREAD

**Issue by yixinagqingyuan** [ckeditor/ckeditor5-vue#97]
@ckeditor/ckeditor5-upload/ ，The plug-in is taken out of node_modules and referenced in src, resulting in an error. 
 
The contents of the error report are as follows.

plugincollection.js?6e03:358 plugincollection-load: It was not possible to load the plugin. Read more:

Uncaught (in promise) CKEditorError: plugincollection-plugin-name-conflict: Two plugins with the same name were loaded. Read more:

**Comment by Mgsy** [comment]
Can you share your CKEditor 5 configuration? The description doesn't provide much information, so it will be helpful to see the code and check whether something is incorrect.

**Comment by cenxky** [comment]
@yixinagqingyuan This is because the npm package of `ckeditor5-vue` just only contains compiled codes. However `Base64UploadAdapter` and `SimpleUploadAdapter` are es6 module style. Thus webpack cannot remove duplicated codes. 

You can create an uploader instead of offical's. Here is an example of what I did:

```html
<ckeditor 
  :editor="editor" 
  v-model="editorData" 
  :config="editorConfig" 
  @ready="setUploader">
</ckeditor>
```

```javascript
import { Instance } from "flexivue"
import ClassicEditor from '@ckeditor/ckeditor5-build-classic'
import uploadAdapter from '.../utils/ckeditor-uploader'

// Load Zh-CN languge
import '@ckeditor/ckeditor5-build-classic/build/translations/zh-cn'

export default class extends Instance {
  data = {
    editor: ClassicEditor,
    editorData: "",
    editorConfig: { language: 'zh-cn' }
  }

  methods = {
    setUploader(editor) {
      editor
        .plugins
        .get('FileRepository')
        .createUploadAdapter = (loader) => new uploadAdapter(loader)
    }
  }
}
```

```javascript
// .../utils/ckeditor-uploader.js
import axios from './axios'

export default function (loader) {
  this.loader = loader

  this.upload = () => {
    return this.loader.file.then(file => {
      let formData = new FormData()
      formData.append('file', file)

      const config = {
        headers: {
          'Content-Type': 'multipart/form-data'
        },
        onUploadProgress: (evt) => {
          if (evt.lengthComputable) {
            this.loader.uploadTotal = evt.total
            this.loader.uploaded = evt.loaded
          }
        }
      }

      return axios
        .post('/attachments/upload', formData, config)
        .then(data => ({ default: data.url }))
        .catch(error => layer.msg("Upload failed"))
    })
  }

  this.abort = () => {
    layer.msg("Cancled")
  }
}

```

**Comment by yixinagqingyuan** [comment]
Big man, are they Chinese? May I consult you in Chinese? I have a lot of questions to answer.

**Comment by yixinagqingyuan** [comment]
This is the full configuration address.：https://gitee.com/yangyongsheng/ckeditor.git，Trouble to see

**Comment by cenxky** [comment]
@yixinagqingyuan  Sure, contact me via Gmail: cenxky
